// Versioned asset pipeline.
//   assets/            -> versioned source of every static media file (images, video, fonts, licenses)
//   dist/assets/       -> generated by the build (copy of assets/ + generated subtitles .vtt)
// Rules enforced here (the build fails with a readable list when broken):
//   * dist/ is always deleted and rebuilt; nothing is read from a previous build.
//   * every /assets/... reference in sources and in the generated site must exist,
//     with EXACT letter case (Linux / Cloudflare are case-sensitive, Windows is not).
//   * no generated file may exceed Cloudflare Pages' 25 MiB per-file limit.
import fs from 'node:fs';
import path from 'node:path';

export const ASSET_SRC = 'assets';
export const DIST = 'dist';
export const ORIGIN_RE = 'https?://(?:www\\.)?fulviocorrea\\.com\\.co';
const MEDIA_EXT = /\.(webp|png|jpe?g|gif|avif|svg|ico|mp4|webm|vtt|woff2?|ttf|otf|pdf)$/i;
const MAX_FILE_BYTES = 25 * 1024 * 1024;
const MAX_FILES = 20000;
const IGNORED_SOURCE_FILES = /(^|\/)(\.|README\.md$|Thumbs\.db$|desktop\.ini$)/i;

// Recursive listing with POSIX separators, relative to dir.
export function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter(d => d.isFile())
    .map(d => path.relative(dir, path.join(d.parentPath ?? d.path, d.name)).split(path.sep).join('/'))
    .sort();
}

export function sourceAssets() {
  return walk(ASSET_SRC).filter(f => !IGNORED_SOURCE_FILES.test(f));
}

// 1) Start from an empty dist/ and copy the versioned assets into dist/assets/.
export function prepareDist() {
  fs.rmSync(DIST, { recursive: true, force: true });
  const files = sourceAssets();
  for (const f of files) {
    const to = path.join(DIST, 'assets', ...f.split('/'));
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(ASSET_SRC, ...f.split('/')), to);
  }
  return files.length;
}

// Pixel dimensions from the file header (WebP, PNG, JPEG, GIF). No dependencies.
export function imageSize(file) {
  const b = fs.readFileSync(file);
  if (b.toString('ascii', 0, 4) === 'RIFF' && b.toString('ascii', 8, 12) === 'WEBP') {
    const chunk = b.toString('ascii', 12, 16);
    if (chunk === 'VP8X') return { width: 1 + b.readUIntLE(24, 3), height: 1 + b.readUIntLE(27, 3) };
    if (chunk === 'VP8L') { const n = b.readUInt32LE(21); return { width: (n & 0x3fff) + 1, height: ((n >> 14) & 0x3fff) + 1 }; }
    if (chunk === 'VP8 ') return { width: b.readUInt16LE(26) & 0x3fff, height: b.readUInt16LE(28) & 0x3fff };
  }
  if (b.readUInt32BE(0) === 0x89504e47) return { width: b.readUInt32BE(16), height: b.readUInt32BE(20) };
  if (b.toString('ascii', 0, 3) === 'GIF') return { width: b.readUInt16LE(6), height: b.readUInt16LE(8) };
  if (b[0] === 0xff && b[1] === 0xd8) {
    let i = 2;
    while (i < b.length) {
      if (b[i] !== 0xff) { i++; continue; }
      const m = b[i + 1], len = b.readUInt16BE(i + 2);
      if (m >= 0xc0 && m <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(m)) return { width: b.readUInt16BE(i + 7), height: b.readUInt16BE(i + 5) };
      i += 2 + len;
    }
  }
  return null;
}

// data/images.json stays the curated metadata file; images that are not listed there
// (e.g. a new blog cover added by an agent) get their real dimensions from the file.
let metaCache;
export function imageMeta() {
  if (metaCache) return metaCache;
  const meta = JSON.parse(fs.readFileSync('data/images.json', 'utf8'));
  for (const f of sourceAssets()) {
    if (meta[f] || !/\.(webp|png|jpe?g|gif)$/i.test(f)) continue;
    const size = imageSize(path.join(ASSET_SRC, ...f.split('/')));
    if (size) meta[f] = { ...size, bytes: fs.statSync(path.join(ASSET_SRC, ...f.split('/'))).size };
  }
  return (metaCache = meta);
}

const refRe = new RegExp(`(?:${ORIGIN_RE})?/assets/[A-Za-z0-9._~%+@/-]*[A-Za-z0-9_~%+@-]`, 'g');
const clean = r => decodeURIComponent(r.replace(new RegExp('^' + ORIGIN_RE), '').replace(/^\/assets\//, ''));

// Collect "/assets/…" references (and bare media file names in JSON data) from source files.
function jsonBareNames(value, out, key = '') {
  if (key.startsWith('_')) return; // _itemSchema, _todo … are editorial templates, not published data
  if (typeof value === 'string') { if (!value.includes('/') && MEDIA_EXT.test(value)) out.push(value); }
  else if (Array.isArray(value)) value.forEach(v => jsonBareNames(v, out));
  else if (value && typeof value === 'object') for (const [k, v] of Object.entries(value)) jsonBareNames(v, out, k);
}
export function sourceReferences() {
  const files = [
    ...walk('data').map(f => 'data/' + f),
    ...walk('content').map(f => 'content/' + f),
    ...fs.readdirSync('.').filter(f => /\.(css|mjs|js)$/.test(f) && !/-test\.mjs$/.test(f)),
    ...walk('server').map(f => 'server/' + f),
    ...walk('functions').map(f => 'functions/' + f),
  ].filter(f => /\.(json|md|css|mjs|js)$/.test(f));
  const refs = [];
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    const draft = file.startsWith('content/blog/') && /^draft:\s*true\s*$/m.test(text);
    for (const m of text.matchAll(refRe)) { const asset = clean(m[0]); if (/\.[a-z0-9]+$/i.test(asset)) refs.push({ asset, from: file, draft }); }
    if (file.endsWith('.json') && !file.endsWith('data/images.json')) {
      const names = []; jsonBareNames(JSON.parse(text), names);
      for (const n of names) refs.push({ asset: n, from: file, draft });
    }
  }
  return refs;
}

function formatMissing(list, where) {
  const byAsset = new Map();
  for (const r of list) byAsset.set(r.asset, [...(byAsset.get(r.asset) || []), r.from]);
  return [...byAsset].map(([a, from]) => `  - /assets/${a}${hint(a, where)}\n      referenced in: ${[...new Set(from)].slice(0, 6).join(', ')}${from.length > 6 ? ' …' : ''}`).join('\n');
}
function hint(asset, where) {
  const ci = where.find(f => f.toLowerCase() === asset.toLowerCase());
  return ci ? `   (case mismatch: file is "${ci}")` : '';
}

// Generated during the build (from content/videos/*.json), so they are not versioned sources.
const GENERATED = /\.vtt$/i;

// 2) Before rendering: every referenced asset must exist in assets/ (exact case).
export function checkSourceAssets() {
  const have = new Set(sourceAssets()), list = [...have];
  const refs = sourceReferences().filter(r => !GENERATED.test(r.asset));
  const missing = refs.filter(r => !have.has(r.asset) && !r.draft);
  const draftMissing = refs.filter(r => !have.has(r.asset) && r.draft);
  const warnings = draftMissing.map(r => `Draft ${r.from} references missing /assets/${r.asset} (allowed while draft: true).`);
  const badNames = list.filter(f => MEDIA_EXT.test(f) && /[A-Z\s\\]/.test(f));
  warnings.push(...badNames.map(f => `Asset name "${f}" contains uppercase/space characters; prefer lowercase-kebab-case.`));
  if (missing.length) throw Error(`Missing local assets. These files are referenced but do not exist in ${ASSET_SRC}/ (names are case-sensitive):\n${formatMissing(missing, list)}\nAdd the files under ${ASSET_SRC}/ (same path as the URL after /assets/) or fix the reference.`);
  return { count: have.size, references: new Set(refs.map(r => r.asset)).size, warnings };
}

// 3) After rendering: scan the whole generated site.
export function checkDistAssets() {
  const files = walk(DIST), have = new Set(files), missing = [], warnings = [];
  const textFiles = files.filter(f => /\.(html|css|js|xml|txt|json|webmanifest|vtt)$/.test(f) || /(^|\/)_(headers|redirects)$/.test(f));
  const used = new Set();
  for (const f of textFiles) {
    const text = fs.readFileSync(path.join(DIST, f), 'utf8');
    for (const m of text.matchAll(refRe)) {
      const asset = clean(m[0]);
      if (!/\.[a-z0-9]+$/i.test(asset)) continue; // directories / wildcard rules (e.g. _headers)
      used.add('assets/' + asset);
      if (!have.has('assets/' + asset)) missing.push({ asset, from: 'dist/' + f });
    }
    // Relative url() in CSS must also resolve.
    if (f.endsWith('.css')) for (const m of text.matchAll(/url\(\s*['"]?([^'")]+)['"]?\s*\)/g)) {
      const u = m[1]; if (/^(data:|https?:|#)/.test(u)) continue;
      const target = u.startsWith('/') ? u.slice(1) : path.posix.join(path.posix.dirname(f), u);
      if (!have.has(decodeURIComponent(target.split(/[?#]/)[0]))) missing.push({ asset: target.replace(/^assets\//, ''), from: 'dist/' + f });
    }
  }
  const tooBig = files.filter(f => fs.statSync(path.join(DIST, f)).size > MAX_FILE_BYTES);
  const errors = [];
  if (missing.length) errors.push(`Generated pages reference assets that are not in dist/assets (names are case-sensitive):\n${formatMissing(missing, files.filter(f => f.startsWith('assets/')).map(f => f.slice(7)))}`);
  if (tooBig.length) errors.push(`Files larger than Cloudflare Pages' 25 MiB limit:\n${tooBig.map(f => '  - dist/' + f).join('\n')}`);
  if (files.length > MAX_FILES) errors.push(`dist/ has ${files.length} files (Cloudflare Pages limit: ${MAX_FILES}).`);
  for (const f of files) if (/(^|\/)(\.env|\.git|node_modules|.*\.log$|.*\.bak$|.*\.zip$)/.test(f)) errors.push('Forbidden file in dist/: ' + f);
  if (errors.length) throw Error(errors.join('\n'));
  const unused = files.filter(f => f.startsWith('assets/') && !used.has(f) && !/\.(txt|md)$/.test(f));
  if (unused.length) warnings.push(`${unused.length} asset(s) copied but not referenced by any page: ${unused.map(f => f.slice(7)).join(', ')}`);
  return { files: files.length, assets: files.filter(f => f.startsWith('assets/')).length, references: used.size, warnings };
}
