import {patientVideos,patientCards,patientWatch} from './patient-videos.mjs';
import {procedureVideo} from './procedure-video.mjs';
import {liposuctionView,liposuctionSchema} from './liposuction-view.mjs';
import {internationalView} from './international-view.mjs';
import {facilityView,clinicContact} from './facility-view.mjs';import {contactView,officePhones,officeHours} from './contact-view.mjs';
import {physicianNode,membershipView,editorialAuthor,authorView,profileNode} from './practice-view.mjs';
import fs from 'node:fs';import {read,write,esc,markdown,posts} from './editorial.mjs';
import {imageMeta,imageSize} from './assets.mjs';
import {localizeEsOutput,localizeRedirectRules,localizePath} from './routes.mjs';
import {assetRedirects,ogForPage} from './media.mjs';
const origin=read('config.json').origin,practice=read('data/practice.json'),production=process.env.SITE_ENV==='production';
// Hosting: Cloudflare Pages (see cloudflare.mjs). Production is selected by site-env.mjs.
const data=fs.readdirSync('content/procedures').map(f=>read('content/procedures/'+f)),blog=posts().filter(p=>!p.draft),clusters=read('content/clusters.json'),images=imageMeta();
const pages=new Map(read('pages.json').map(p=>[p.route,p]));const t=(l,a,b)=>l==='en'?a:b;
const proc=(l,slug)=>data.find(p=>p.lang===l&&p.slug===slug);const route=p=>`/${p.lang}/procedures/${p.slug}/`,postRoute=p=>`/${p.lang}/blog/${p.slug}/`;
const base=Object.fromEntries(['en','es'].map(l=>[l,fs.readFileSync(`dist/${l}/about/index.html`,'utf8')]));
const image=(p)=>{const m=images[p.image],pr=p.image.match(/^(.+-portrait-)(\d+)\.webp$/);if(!pr)return `<img src="/assets/${p.image}" alt="${esc(p.imageAlt)}" width="${m.width}" height="${m.height}" loading="lazy" decoding="async">`;const set=ext=>`/assets/${pr[1]}480.${ext} 480w, /assets/${pr[1]}${pr[2]}.${ext} ${pr[2]}w`,sizes='(max-width: 700px) 88vw, 560px';return `<picture><source type="image/avif" srcset="${set('avif')}" sizes="${sizes}"><img src="/assets/${p.image}" alt="${esc(p.imageAlt)}" width="${m.width}" height="${m.height}" srcset="${set('webp')}" sizes="${sizes}" data-fixed-srcset="1" loading="lazy" decoding="async"></picture>`;};
function create(l,slug,title,description,body,extra={}){const r=`/${l}/${slug}`,file='dist'+r+'index.html';write(file,base[l].replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${body}</main>`).replace(/<title>.*?<\/title>/,`<title>${esc(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(description)}">`));pages.set(r,{route:r,file,lang:l,noindex:false,ads:false,updated:'2026-09-26',schemas:[],...extra});}
const shortCards=(items,l)=>items.length?`<ul class="cluster-links">${items.map(p=>`<li><a href="${postRoute(p)}">${esc(p.title)}</a></li>`).join('')}</ul>`:'';
const clinicalKeys={summary:['Overview','Resumen'],candidates:['Candidates','¿Para quién se considera?'],technique:['Technique','Técnica'],anesthesia:['Anesthesia','Anestesia'],facility:['Facility','Centro quirúrgico'],duration_surgery:['Surgery duration','Duración de la cirugía'],suggested_stay_cartagena:['Stay in Cartagena','Estancia en Cartagena'],whats_included:['What is included','Qué incluye'],risks_specific:['Specific risks','Riesgos específicos']};
const reviewed=(p,l)=>p.reviewed_by&&p.review_date?`<p class="reviewed">${t(l,'Medically reviewed by','Revisado médicamente por')} ${esc(p.reviewed_by)} · ${esc(p.review_date)}</p>`:'';
for(const p of data){const l=p.lang,title=p.h1||p.name+t(l,' in Cartagena',' en Cartagena'),links=blog.filter(x=>x.lang===l&&(clusters[l][p.slug]||[]).includes(x.slug)).sort((a,b)=>b.updated.localeCompare(a.updated));const faqs=p.faqs.filter(f=>f.q&&f.a);const content=Object.entries(clinicalKeys).filter(([k])=>p[k]).map(([k,label])=>`<section><h2>${label[l==='en'?0:1]}</h2>${markdown(p[k])}</section>`).join('');
let special='';if(p.slug==='breast-lift-reduction'||p.slug==='breast-augmentation'){const other=proc(l,p.slug==='breast-lift-reduction'?'breast-augmentation':'breast-lift-reduction');special=`<aside class="intent-link">${t(l,'Looking for','¿Buscas')} ${esc(other.name.toLowerCase())}${t(l,'? Explore','? Consulta')} <a href="${route(other)}">${esc(other.name.toLowerCase())+t(l,' in Cartagena',' en Cartagena')}</a>.</aside>`;}
const body=`<section class="page-hero wrap" data-surface="charcoal"><p class="eyebrow">${t(l,'Procedure','Procedimiento')}</p><h1>${esc(title)}</h1><p class="post-dates">${t(l,'Updated','Actualizado el')} <time datetime="${p.updated_at}">${p.updated_at}</time></p>${reviewed(p,l)}</section><section class="section wrap no-top detail-grid" data-surface="black"><div class="detail-image">${image(p)}</div><article data-procedure-content>${content}${p.recovery_timeline.length?`<section><h2>${t(l,'Recovery timeline','Recuperación por semanas')}</h2>${p.recovery_timeline.filter(x=>x.text).map(x=>`<h3>${esc(x.week)}</h3>${markdown(x.text)}`).join('')}</section>`:''}${p.combinations.filter(x=>proc(l,x.slug)?.offeredConfirmed&&x.text).map(x=>`<p>${esc(x.text)} <a href="${route(proc(l,x.slug))}">${esc(proc(l,x.slug).name)}</a></p>`).join('')}${faqs.length?`<section><h2>${t(l,'Questions about','Preguntas sobre')} ${esc(p.name.toLowerCase())}</h2>${faqs.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</section>`:''}<aside data-shared>${authorView(practice,l)}${special}<a class="button" data-cta="procedure-consult" href="/${l}/book-consultation/?procedure=${p.slug}">${t(l,'Request a consultation','Solicitar valoración')}</a></aside></article></section>${Object.keys(clinicalKeys).some(k=>p[k])||faqs.length?`<section class="section wrap sources" data-shared><h2>${t(l,'Sources','Fuentes')}</h2><ul>${p.sources.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a></li>`).join('')}</ul></section>`:''}${links.length?`<section class="section wrap" data-shared data-surface="plum"><h2>${t(l,'Guides and frequently asked questions','Guías y preguntas frecuentes')}</h2>${shortCards(links,l)}</section>`:''}`;
const videoPage=procedureVideo(body,p,origin);
create(l,`procedures/${p.slug}/`,p.seo_title||title,p.description,p.slug==='liposuction'?liposuctionView(body,l):videoPage.body,{noindex:!p.offeredConfirmed,procedure:p.slug,updated:p.updated_at,schemas:[...videoPage.schemas,...(p.slug==='liposuction'?[liposuctionSchema(origin,l)]:[]),...(p.reviewed_by&&p.review_date&&practice.authorApproved?[{'@context':'https://schema.org','@type':'MedicalWebPage',url:origin+route(p),name:p.seo_title||title,inLanguage:l,lastReviewed:p.review_date,reviewedBy:{'@id':origin+'/#physician'},about:{'@type':'MedicalProcedure',name:p.name}}]:[]),{'@context':'https://schema.org','@type':'MedicalProcedure',name:p.name,...(p.summary?{description:p.summary.split(/\n\s*\n/)[0].replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[*_`#]/g,'').trim()}:{}),url:origin+route(p)},...(faqs.length?[{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}]:[])]});}
const sms=l=>`<label class="consent sms-optin"><input type="checkbox" name="sms_consent" value="true"><span>${t(l,'I agree to receive SMS about my enquiry. Frequency varies; message/data rates may apply. Reply STOP to cancel or HELP for help. Consent is optional and not a condition of purchase.','Acepto recibir SMS sobre mi solicitud. La frecuencia varía y pueden aplicarse tarifas. Responde STOP para cancelar o HELP para ayuda. Es opcional y no condiciona la compra.')} <a href="/${l}/sms/">${t(l,'SMS terms','Condiciones SMS')}</a>.</span></label>`;
for(const l of ['en','es']){create(l,l==='en'?'thank-you/':'gracias/',t(l,'Thank you for your enquiry','Gracias por tu solicitud'),t(l,'Your request has been received.','Recibimos tu solicitud.'),`<section class="page-hero wrap"><h1>${t(l,'Thank you.','Gracias.')}</h1><p id="thanks-confirmation">${t(l,'If you submitted a request successfully, our team will contact you.','Si enviaste tu solicitud correctamente, el equipo se pondrá en contacto contigo.')}</p><a href="/${l}/">${t(l,'Return home','Volver al inicio')}</a></section>`,{noindex:true,alternate:l==='en'?'/es/gracias/':'/en/thank-you/'});
for(const p of data.filter(p=>p.lang===l&&p.offeredConfirmed)){const fields=['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','gbraid','wbraid','landing_page','referrer','first_touch','last_touch','conversion_page','lead_id'];const f=`<form id="consultation-form" data-form="ads-consultation"><div class="ads-fields"><label>${t(l,'Name','Nombre')}<input name="name" autocomplete="name" maxlength="100" required></label><label>${t(l,'Email','Correo')}<input name="email" type="email" autocomplete="email" maxlength="254" required></label><label>${t(l,'Phone with country code','Teléfono con código de país')}<input name="phone" type="tel" autocomplete="tel" placeholder="+57 300 123 4567" maxlength="30" required></label></div><select name="procedure" hidden><option value="${p.slug}">${p.name}</option></select><details class="ads-optional"><summary>${t(l,'Country and message (optional)','País y mensaje (opcional)')}</summary><label>${t(l,'Country','País')}<input name="country" maxlength="100"></label><label>${t(l,'Message','Mensaje')}<textarea name="message" maxlength="3000"></textarea></label></details><label class="consent"><input type="checkbox" name="contact_consent" required><span>${t(l,'I agree to be contacted about this enquiry.','Acepto que me contacten sobre esta solicitud.')} <a href="/${l}/privacy/">${t(l,'Privacy','Privacidad')}</a>.</span></label>${sms(l)}<div class="honeypot" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div>${fields.map(k=>`<input type="hidden" name="${k}">`).join('')}<input type="hidden" name="language" value="${l}"><button class="button" id="submit-consultation" type="submit">${t(l,'Request my consultation','Solicitar mi valoración')}</button><p id="form-status" role="status"></p></form>`;
create(l,`ads/${p.slug}/`,p.name+t(l,' consultation in Cartagena',': valoración en Cartagena'),p.description,`<section class="ads-lead wrap"><div><p class="eyebrow">Dr. Fulvio Correa · Cartagena</p><h1>${esc(p.name)}</h1><a href="${route(p)}">${t(l,'Complete guide to ','Guía completa de ')+esc(p.name.toLowerCase())+t(l,' in Cartagena',' en Cartagena')}</a></div>${f}</section>`,{noindex:true,ads:true,procedure:p.slug});}
}
for(const lang of ['en','es']){const v=internationalView(lang,read('data/international-patients.json'),practice,data,blog);create(lang,'international-patients/',v.title,v.description,v.body,{schemas:v.schemas,cover:'/assets/blog-cartagena-medical-tourism.webp'});}
for(const lang of ['en','es']){const v=facilityView(lang,read('data/facility.json'),practice,origin);create(lang,'capri-clinic/',v.title,v.description,v.body,{schemas:v.schemas,cover:'/assets/dr-fulvio-correa-logo.png'});}
for(const lang of ['en','es']){const v=contactView(lang,practice,read('data/facility.json'),origin);create(lang,'contact/',v.title,v.description,v.body,{schemas:v.schemas,updated:'2026-09-28'});}
for(const lang of ['en','es']){const title=t(lang,'Patient Stories, Cartagena','Experiencias en Cartagena');const h1=t(lang,'Patient stories from Cartagena','Experiencias de pacientes en Cartagena');create(lang,'testimonials/',title,t(lang,'Watch patient experiences shared on Dr. Fulvio Correa’s channel, with English and Spanish subtitles and readable transcripts.','Conoce experiencias del canal del Dr. Fulvio Correa, con subtítulos en español e inglés y transcripciones para leer.'),`<section class="page-hero wrap"><h1>${h1}</h1><p>${t(lang,'Personal stories. Individual experiences and results vary.','Historias personales. Las experiencias y los resultados son individuales.')}</p></section><section class="section wrap no-top"><h2>${t(lang,'Watch patient experiences','Ver experiencias de pacientes')}</h2>${patientCards(lang)}</section>`);for(const video of patientVideos()){const v=patientWatch(video,lang,origin);create(lang,`testimonials/${video.slug}/`,v.title,v.description,v.body,{schemas:v.schemas,cover:video.poster,updated:video.uploadDate.slice(0,10)});}}
const redirects={'/':'/en/','/home-plastic-surgery-colombia-cartagena':'/en/','/plastic-surgery-colombia':'/en/','/plastic-surgery-colombia-cartagena-staff':'/en/about/','/plastic-surgery-colombia-cartagena-travel':'/en/international-patients/','/draft-travel-es':'/es/international-patients/','/blog':'/en/blog/','/blog/tag/*':'/en/blog/','/blog/category/*':'/en/blog/','/blog/author/*':'/en/blog/','/privacy-policy-1485':'/en/privacy/','/terms--conditions-5647':'/en/terms/','/sms-concent-4396':'/en/sms/','/terms-and-conditions':'/en/terms/','/privacy-policies':'/en/privacy/'};
for(const p of data.filter(p=>p.lang==='en'))redirects['/plastic-surgery-colombia-cartagena-'+p.slug]=route(p);redirects['/plastic-surgery-colombia-cartagena-abdominoplasty']='/en/procedures/tummy-tuck/';delete redirects['/plastic-surgery-colombia-cartagena-breast-lift-reduction'];Object.assign(redirects,{'/plastic-surgery-colombia-cartagena-mammoplasty':'/en/procedures/breast-lift-reduction/','/en/procedures/mammoplasty':'/en/procedures/breast-lift-reduction/','/es/procedures/mammoplasty':'/es/procedures/breast-lift-reduction/','/procedures/mammoplasty':'/en/procedures/breast-lift-reduction/','/en/ads/mammoplasty':'/en/ads/breast-lift-reduction/','/es/ads/mammoplasty':'/es/ads/breast-lift-reduction/','/ads/mammoplasty':'/en/ads/breast-lift-reduction/'});
for(const p of blog)redirects['/post/'+p.slug]=postRoute(p);
const localize=(r,l)=>{if(!r.startsWith('/en/'))return r;const other=r.replace('/en/',`/${l}/`);return pages.has(other)?other:r;};
const authorName=l=>practice.authorApproved?practice.name:t(l,'Editorial team · Dr. Fulvio Correa’s practice','Equipo editorial · Consultorio Dr. Fulvio Correa');
for(const p of pages.values()){let h=fs.readFileSync(p.file,'utf8'),l=p.lang,other=l==='en'?'es':'en';const post=blog.find(x=>postRoute(x)===p.route),procedure=p.procedure&&!p.ads?proc(l,p.procedure):null;
if(p.route===`/${l}/book-consultation/`)p.noindex=true;
if(p.route===`/${l}/`){h=h.replace(/(<section class="testimonials section wrap"[\s\S]*?<\/section>)/,`$1<section class="section wrap" data-surface="charcoal"><h2>${t(l,'Their experience, in their words.','Su experiencia, en sus palabras.')}</h2>${patientCards(l)}<a class="textlink" href="/${l}/testimonials/">${t(l,'Explore patient experiences','Explorar experiencias')} ↗</a></section>`);}
if(p.route===`/${l}/international-patients/`)h=h.replace('</main>',`<section class="section wrap" data-surface="charcoal"><h2>${t(l,'Patient experiences','Experiencias de pacientes')}</h2>${patientCards(l)}<a href="/${l}/testimonials/">${t(l,'All patient stories','Todas las experiencias')} ↗</a></section></main>`);
// Clinic and consultation office are distinct places. Share a discoverable facility page.
h=h.replace('</div></div><div class="footer-bottom wrap">',()=>`<p>${officePhones(practice,l,'footer')}${practice.hoursBrief?.[l]?'<br>'+officeHours(practice,l,true):''}<br><a href="/${l}/contact/">${t(l,'All contact details','Todos los datos de contacto')}</a></p></div></div><div class="footer-bottom wrap">`);
if(!p.ads){h=h.replace(`<a href="/${l}/faq/">`,`<a href="/${l}/capri-clinic/">${t(l,'Surgical clinic · CAPRI','Clínica quirúrgica · CAPRI')}</a><a href="/${l}/faq/">`);}
if(procedure||p.route===`/${l}/about/`||p.route===`/${l}/international-patients/`){h=h.replace('</main>',`<section class="section" data-surface="charcoal" data-shared><div class="wrap"><p class="eyebrow">${t(l,'Your surgical setting','Tu centro quirúrgico')}</p><h2>${t(l,'Surgery at CAPRI Clinic','Tu cirugía en Clínica CAPRI')}</h2><p>${t(l,'Dr. Fulvio Correa performs surgery at CAPRI Clinic in Cartagena. Learn how the surgical clinic differs from your consultation location.','El Dr. Fulvio Correa opera en la Clínica CAPRI de Cartagena. Conoce la diferencia entre la clínica quirúrgica y el lugar de tu valoración.')}</p>${clinicContact(l,read('data/facility.json'))}<a class="textlink" href="/${l}/capri-clinic/">${t(l,'Explore the surgical clinic','Conoce la clínica quirúrgica')} ↗</a></div></section></main>`);}
if(post){if(!proc(l,post.procedure))throw Error('Post missing pillar: '+post.slug);const pillar=proc(l,post.procedure);const related=post.related.map(slug=>blog.find(x=>x.lang===l&&x.slug===slug)).filter(Boolean).slice(0,4);const coverName=post.cover.replace('/assets/','');const coverAvif=coverName.replace(/\.webp$/i,'.avif');const coverImg=image({image:coverName,imageAlt:post.coverAlt});const coverHtml=fs.existsSync('assets/'+coverAvif)?`<picture><source type="image/avif" srcset="/assets/${coverAvif}">${coverImg}</picture>`:coverImg;const coverExtras=['.avif','-og.webp','-og.avif'].map(s=>coverName.replace(/\.webp$/i,s)).filter(n=>fs.existsSync('assets/'+n));const twin=blog.find(x=>x.lang===other&&x.slug===post.twin);p.alternate=twin?postRoute(twin):null;
const callout=`<aside class="pillar-link">${t(l,'Complete guide:','Guía completa:')} <a href="${route(pillar)}">${esc(pillar.name.toLowerCase())+t(l,' in Cartagena',' en Cartagena')}</a></aside>`;
let body=markdown(post.body);const first=body.indexOf('</p>');body=first>=0?body.slice(0,first+4)+callout+body.slice(first+4):callout+body;
const article=`<article class="article article-body wrap"><p class="post-dates">${t(l,'Updated','Actualizado el')} <time datetime="${post.updated}">${post.updated}</time></p>${authorView(practice,l)}${reviewed(post,l)}<figure>${coverHtml}<figcaption class="small-label">${t(l,'Illustrative photograph','Fotografía ilustrativa')}</figcaption></figure>${body}</article><section class="section wrap" data-shared><h2>${t(l,'Related reading','Lecturas relacionadas')}</h2>${shortCards(related,l)}<a class="button" data-cta="post-consult" href="/${l}/book-consultation/?procedure=${pillar.slug}">${t(l,'Request a consultation about ','Solicitar valoración de ')+esc(pillar.name.toLowerCase())}</a></section>`;
h=h.replace(/<article class="article article-body wrap">[\s\S]*<\/main>/,article+'</main>');p.schemas=[{'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,datePublished:post.date,dateModified:post.updated,inLanguage:l,image:coverExtras.length?[origin+post.cover,...coverExtras.map(n=>origin+'/assets/'+n)]:origin+post.cover,mainEntityOfPage:origin+p.route,author:editorialAuthor(practice,l,origin),publisher:{'@type':'Organization',name:practice.name,url:origin+`/${l}/`,logo:{'@type':'ImageObject',url:origin+'/assets/dr-fulvio-correa-logo.png'}}}];}
// Confirmed procedures are the single source for navigation, hub and form options.
const confirmed=data.filter(x=>x.lang===l&&x.offeredConfirmed);const nav=`<details class="procedure-menu"><summary>${t(l,'Procedures','Procedimientos')}</summary><div><a href="/${l}/procedures/">${t(l,'All procedures','Todos los procedimientos')}</a>${confirmed.map(x=>`<a href="${route(x)}">${esc(x.name)}</a>`).join('')}</div></details>`;
h=h.replace(new RegExp(`<a href="/${l}/procedures/">${t(l,'Procedures','Procedimientos')}</a>`),nav);
h=h.replace(/(<select name="procedure">)[\s\S]*?(<\/select>)/g,`$1<option value="other">${t(l,'Other / guidance','Otro / orientación')}</option>${confirmed.map(x=>`<option value="${x.slug}"${p.ads&&x.slug===p.procedure?' selected':''}>${esc(x.name)}</option>`).join('')}$2`);
if(p.route===`/${l}/book-consultation/`)h=h.replace('<button class="button" id="submit-consultation"',sms(l)+'<button class="button" id="submit-consultation"');
// Widget only hands off to messaging; no SMS subscription is created here.
for(const category of read('data/categories.json'))if(!blog.some(x=>x.lang===l&&x.category===category.en))h=h.replace(new RegExp(`<a href="/${l}/blog/category/${category.slug}/">[\\s\\S]*?<\\/a>`,'g'),'');
// Descriptive local source links, with no old-host hrefs.
h=h.replace(/href="https?:\/\/(?:www\.)?fulviocorrea\.com\.co([^"\s]*)"/g,(full,suffix)=>{const u=new URL(suffix||'/',origin),key=u.pathname.replace(/\/$/,'')||'/';const r=redirects[key]|| (pages.has(u.pathname)?u.pathname:pages.has(u.pathname+'/')?u.pathname+'/':null);if(!r)throw Error('Unmapped old href '+u.pathname);return `href="${localize(r,l)+u.search+u.hash}"`;});
h=h.replace(/Official practice website|Web oficial del consultorio|official practice website|web oficial del consultorio/g,t(l,'Practice information','Información del consultorio'));
// Foreign editorial links point to an actual twin; otherwise to the same-language blog hub.
h=h.replace(/<a\b([^>]*?)href="(\/(en|es)\/[^"?#]*)([^"\s]*)"([^>]*)>/g,(full,a,r,destLang,tail,z)=>{if(destLang===l||/data-language/.test(a+z))return full;const entry=blog.find(x=>postRoute(x)===r);const twin=entry&&blog.find(x=>x.lang===l&&x.slug===entry.twin);const destination=twin?postRoute(twin):localize(r.replace(`/${other}/`,'/en/'),l);return `<a${a}href="${destination.startsWith('/'+l+'/')?destination:'/'+l+'/blog/'}${tail}"${z}>`;});
const counterpart=p.alternate===null?null:p.alternate||p.route.replace(`/${l}/`,`/${other}/`);const otherPage=counterpart&&pages.get(counterpart);const otherOk=!p.noindex&&otherPage&&!otherPage.noindex&&!otherPage.ads;p.alternates=[{lang:l,route:p.route},...(otherOk?[{lang:other,route:counterpart}]:[])];
h=h.replace(/<a\b[^>]*data-language="(en|es)"[^>]*>[\s\S]*?<\/a>/g,(full,lang)=>{const r=p.alternates.find(a=>a.lang===lang)?.route;return r?full.replace(/href="[^"]*"/,`href="${r}"`):'';});
const oldTitle=h.match(/<title>(.*?)<\/title>/)[1],cleanTitle=oldTitle.replace(/ \| Dr\. Fulvio Correa$/,'');let title=cleanTitle.length+20<=60?cleanTitle+' | Dr. Fulvio Correa':cleanTitle;
if(title.length>60){const custom=post?{'tummy-tuck-colombia':'Tummy Tuck in Colombia: Planning Your Consultation','abdominoplastia-colombia':'Abdominoplastia en Colombia: prepara tu valoración','breast-augmentation-colombia':'Breast Augmentation Colombia: Verify Surgeons','bbl-colombia':'BBL in Colombia: Questions for Your Consultation','liposuction-cartagena':'Liposuction in Cartagena: Patient Guide','mommy-makeover-recovery-time':'Mommy Makeover Recovery: Questions and Planning','tiempo-recuperacion-mommy-makeover':'Recuperación de mommy makeover: preguntas y planificación','how-long-to-stay-after-mommy-makeover':'How Long to Stay After a Mommy Makeover?'}[post.slug]:null;title=custom||cleanTitle.slice(0,57).replace(/\s+\S*$/,'')+'…';}
h=h.replace(/<title>.*?<\/title>/,`<title>${title}</title>`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${title}">`).replace(/<meta property="og:url" content="[^"]*">/,`<meta property="og:url" content="${origin+p.route}">`);
const coverFile=(p.cover||'').replace(/^\/assets\//,'');const ogCompanionName=coverFile.replace(/\.webp$/i,'-og.webp');const ogCompanion=post&&fs.existsSync('assets/'+ogCompanionName)?{src:'/assets/'+ogCompanionName,...(imageSize('assets/'+ogCompanionName)||{width:1200,height:630})}:null;const specialOg=ogForPage(p)||ogCompanion;const coverMeta=images[coverFile];const ogSrc=specialOg?origin+specialOg.src:(p.cover?origin+p.cover:origin+'/assets/'+'og/dr-fulvio-correa-plastic-surgery-cartagena.webp');const ogW=specialOg?specialOg.width:(coverMeta?.width||1200);const ogH=specialOg?specialOg.height:(coverMeta?.height||630);const ogAlt=esc(procedure?procedure.name+' · Cartagena':post?post.title:cleanTitle.replace(/ \| Dr\. Fulvio Correa$/,''));const ogLocales=p.alternates.filter(a=>a.lang!==l&&!(pages.get(a.route)?.noindex)).map(a=>a.lang==='es'?'es_CO':'en_US');h=h.replace(/<meta property="og:image" content="[^"]*">/,`<meta property="og:image" content="${ogSrc}"><meta property="og:image:width" content="${ogW}"><meta property="og:image:height" content="${ogH}"><meta property="og:image:alt" content="${ogAlt}">${ogLocales.map(code=>`<meta property="og:locale:alternate" content="${code}">`).join('')}`);
const description=h.match(/<meta name="description" content="([^"]*)"/)?.[1]||'';h=h.replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${description}">`);
const xDefault=(p.alternates.find(a=>a.lang==='en'&&!(pages.get(a.route)?.noindex))||p.alternates.find(a=>!(pages.get(a.route)?.noindex))||p.alternates[0]);h=h.replace(/<link rel="(?:canonical|alternate)"[^>]*>/g,'').replace('</head>',`<link rel="canonical" href="${origin+p.route}">${p.alternates.map(a=>`<link rel="alternate" hreflang="${a.lang}" href="${origin+a.route}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin+xDefault.route}"></head>`);
h=h.replace(/<meta name="robots" content="[^"]*">/,`<meta name="robots" content="${production&&!p.ads&&!p.noindex?'index, follow':'noindex, nofollow'}">`);
const crumbs=p.route===`/${l}/`?[{name:t(l,'Home','Inicio'),route:p.route}]:[{name:t(l,'Home','Inicio'),route:`/${l}/`},...((procedure||post)?[{name:procedure?t(l,'Procedures','Procedimientos'):'Blog',route:`/${l}/${procedure?'procedures':'blog'}/`}]:[]),{name:procedure?procedure.name:post?post.title:cleanTitle,route:p.route}].filter((c,i,arr)=>arr.findIndex(x=>x.route===c.route)===i);
const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name.replace(/ \| Dr\. Fulvio Correa$/,''),item:origin+c.route}))};
if(procedure||post)h=h.replace('<main id="main">',`<main id="main"><nav class="crumb wrap" aria-label="${t(l,'Breadcrumb','Ruta de navegación')}">${crumbs.map((c,i)=>i===crumbs.length-1?`<span aria-current="page">${esc(c.name)}</span>`:`<a href="${c.route}">${esc(c.name)}</a><span aria-hidden="true">›</span>`).join('')}</nav>`);
const oldSchemas=JSON.parse(h.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)?.[1]||'[]');const physician=physicianNode(practice,origin,l);const schema=[...(physician?[physician]:[]),breadcrumb,...(p.route===`/${l}/about/`?[profileNode(practice,origin,l,localizePath(p.route))]:[]),...(p.schemas||oldSchemas.filter(x=>!['Physician','BreadcrumbList'].includes(x['@type'])))];
h=h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/,`<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`);
h=h.replace(/href="(https:\/\/wa\.me\/[^"?]+)(?:\?text=([^"<>]*))?"/g,(full,base,msg)=>{let text='';try{text=decodeURIComponent(msg||'');}catch{}if(!text.includes('[ref:'))text+=' [ref: '+(p.procedure||p.route.split('/').filter(Boolean).slice(1).join('-')||'home')+'-'+l+']';return `href="${base}?text=${encodeURIComponent(text)}"`;});
if(p.ads)h=h.replace(/<body class="[^"]*"/, '<body class="ads"');
h=h.replace(/Allow measurement to help us understand visits and consultation requests\? Optional tracking stays off unless you accept\./g,'Allow analytics and advertising measurement? Optional tags remain off until you accept.').replace(/¿Permites la medición de visitas y solicitudes de valoración\? El seguimiento opcional permanece desactivado hasta que aceptes\./g,'¿Permites la medición analítica y publicitaria? Las etiquetas opcionales permanecen desactivadas hasta que aceptes.');
// All consultation entry points use Sofia; the legacy form remains only at its noindex URL.
h=h.replace(/<a\b([^>]*?)href="([^"]+)"([^>]*)>([\s\S]*?)<\/a>/g,(full,before,href,after,label)=>{if(/data-contact-channel/.test(before+after)||!(/\/(?:en|es)\/book-consultation\//.test(href)||/^https:\/\/wa\.me\//.test(href)))return full;let selected=p.procedure||post?.procedure||'';try{selected=new URL(href,origin).searchParams.get('procedure')||selected;}catch{}const attrs=(before+after).replace(/\s+(?:target|rel|data-event)="[^"]*"/g,'');return `<button type="button" ${attrs} data-open-contact aria-haspopup="dialog" aria-controls="contact-dialog"${selected?` data-procedure="${esc(selected)}"`:''}>${/WhatsApp/.test(label)?t(l,'Chat with Sofía','Hablar con Sofía'):label}</button>`;});
if(p.ads)h=h.replace(/<form id="consultation-form"[\s\S]*?<\/form>/,`<div class="ads-chat"><p>${t(l,'Speak with Sofía, our virtual assistant, about your consultation. Choose your preferred messaging channel.','Habla con Sofía, nuestra asistente virtual, sobre tu valoración y elige tu canal de contacto preferido.')}</p><button type="button" class="button" data-open-contact data-procedure="${p.procedure}" aria-haspopup="dialog" aria-controls="contact-dialog">${t(l,'Chat with Sofía','Hablar con Sofía')}</button></div>`);
write(p.file,h);}
// Root is English HTML with its EN canonical, with no browser redirect.
write('dist/index.html',fs.readFileSync('dist/en/index.html','utf8'));
for(const p of pages.values())if(p.lang==='en'){const alias=p.route.slice(3);if(alias&&alias!=='/')write('dist'+alias+'index.html',fs.readFileSync(p.file,'utf8'));}
write('dist/404.html',fs.readFileSync('dist/en/404/index.html','utf8'));write('dist/en/404.html',fs.readFileSync('dist/en/404/index.html','utf8'));write('dist/es/404.html',fs.readFileSync('dist/es/404/index.html','utf8'));
let rules=Object.entries(redirects).flatMap(([from,to])=>[{from,to,status:301},...(!from.endsWith('/')&&!from.endsWith('*')?[{from:from+'/',to,status:301}]:[])]);
rules=localizeRedirectRules(rules);
const seenFrom=new Set(rules.map(r=>r.from));
for(const extra of assetRedirects())if(!seenFrom.has(extra.from)){rules.push(extra);seenFrom.add(extra.from);}
// Cloudflare Pages classifies rules in file order (workers-sdk #14694): the first
// splat (*) or placeholder (:name) switches the parser to dynamic mode for good.
// Every later line, including an exact path, counts against the 100-dynamic budget,
// and rules past that budget are silently dropped. Exact paths must come first.
const dynamicFrom=r=>/[*:]/.test(r.from);
rules=[...rules.filter(r=>!dynamicFrom(r)),...rules.filter(dynamicFrom)];
write('migration/redirects.json',JSON.stringify({active:production,productionHostingConfirmed:true,adapter:'cloudflare-pages',redirects:rules},null,2));const text=rules.map(r=>`${r.from} ${r.to} 301`).join('\n')+'\n';write('migration/_redirects.pending',text);if(production)write('dist/_redirects',text);else if(fs.existsSync('dist/_redirects'))fs.unlinkSync('dist/_redirects');
write('migration/redirect-test.txt','# Run after production hostname is selected. Expect one 301, then 200; query strings preserved.\n'+rules.map(r=>`curl -I "${origin+r.from.replace('*','example')}"\n# Expected: 301 Location: ${r.to}\ncurl -I "${origin+r.to.split('?')[0]}"\n# Expected: 200`).join('\n\n'));
const indexed=[...pages.values()].filter(p=>!p.noindex&&!p.ads);
const xroute=p=>p.alternates.find(a=>a.lang==='en'&&!(pages.get(a.route)?.noindex))||p.alternates.find(a=>!(pages.get(a.route)?.noindex))||p.alternates[0];
write('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+indexed.map(p=>`<url><loc>${origin+p.route}</loc><lastmod>${p.updated||'2026-09-26'}</lastmod>${[...p.alternates,{lang:'x-default',route:xroute(p).route}].map(a=>`<xhtml:link rel="alternate" hreflang="${a.lang}" href="${origin+a.route}"/>`).join('')}</url>`).join('')+'</urlset>');
const sccp=practice.societies?.[0];
const proceduresEn=data.filter(p=>p.lang==='en'&&p.offeredConfirmed);
write('dist/llms.txt',[
 `# ${practice.name}`,
 '',
 `> Dr. Fulvio Correa is a plastic surgeon in Cartagena de Indias, Colombia, with ${practice.yearsExperience} years of experience in aesthetic and reconstructive plastic surgery and ${practice.proceduresPerformed} procedures performed. He is a Member (Miembro de Número) of the Sociedad Colombiana de Cirugía Plástica Estética y Reconstructiva (SCCP) and a member of FILACP. Pages on this site are educational and do not replace an individual medical assessment.`,
 '',
 '## Practice',
 `- Name: ${practice.name}`,
 '- Specialty: plastic surgery',
 sccp?`- SCCP: ${sccp.name}, ${sccp.role}. Verify: ${sccp.source}`:'',
 practice.legalName?`- Full name: ${practice.legalName}`:'',
 `- Training: ${practice.education.map(e=>e.en).join('; ')}`,
 ...(practice.credentials||[]).map(c=>`- ${c.name.en}${c.recognizedBy?`, ${c.recognizedBy.name}`:''}${c.dateCreated?` (${c.id==='rethus'?'registered':'awarded'} ${c.dateCreated})`:''}${c.verificationUrl?`. Public lookup: ${c.verificationUrl}`:''}`),
 `- Experience: ${practice.yearsExperience} years in aesthetic and reconstructive plastic surgery; ${practice.proceduresPerformed} procedures performed (official biography).`,
 ...(practice.affiliations||[]).map(a=>`- Also member of: ${a.name} (${a.alternateName})`),
 '- Special interest: breast surgery with tissue-preservation techniques; body contouring.',
 '- Philosophy: "Transform without losing your identity" (Transformar sin perder la identidad); "Preserve before you alter" (Preservar antes que alterar).',
 '- Care model: a multidisciplinary team from the first consultation through post-operative recovery; Colombian and international patients in Cartagena de Indias.',
 `- Biography: ${origin}/en/about/ · ${origin}${localizePath('/es/about/')}`,
 `- Address: ${practice.addressLines.join(', ')}`,
 `- Contact: Sofía, our virtual assistant, can open WhatsApp, Instagram, SMS or Facebook. Phone (Colombia): ${practice.phoneDisplay}. WhatsApp and SMS only (US): ${practice.messagingDisplay}. Contact page: ${origin}/en/contact/ · ${origin}${localizePath('/es/contact/')}`,
 ...[practice.openingHoursText?.en,practice.consultationHoursText?.en].filter(Boolean).map(x=>`- ${x}`),
 (f=>`- Surgery: ${f.name} (CAPRI Clinic), the surgical clinic where Dr. Correa operates; it is not the consultation office at CC Ramblas. Address: ${f.addressLines.en.join(', ')}. Clinic phone (CAPRI, not the doctor\'s office): ${f.telephoneDisplay}. Clinic hours: ${f.openingHoursText.en} Instagram: ${f.sameAs[0]}`)(read('data/facility.json')),
 '',
 '## Procedures',
 ...proceduresEn.map(p=>`- ${p.name}: ${origin}/en/procedures/${p.slug}/ · ${origin}${localizePath('/es/procedures/'+p.slug+'/')}`),
 '',
 '## Indexable pages',
 ...indexed.map(p=>`- [${localizePath(p.route)}](${origin}${localizePath(p.route)})`),
 '',
].filter(Boolean).join('\n'));
write('pages.json',JSON.stringify([...pages.values()],null,2));
localizeEsOutput();
const finalPages=JSON.parse(fs.readFileSync('pages.json','utf8')).map(p=>({...p,route:localizePath(p.route),file:localizePath(p.file),alternate:p.alternate?localizePath(p.alternate):p.alternate,alternates:(p.alternates||[]).map(a=>({...a,route:localizePath(a.route)}))}));
write('pages.json',JSON.stringify(finalPages,null,2));
const plain=html=>html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const full=['# '+practice.name,'','Full text of the public pages. Educational only. SCCP membership and ReTHUS registration (Colombian Ministry of Health) are the published credentials. Do not treat video transcripts as verified claims.','',];
for(const p of finalPages.filter(p=>!p.noindex&&!p.ads)){const file=p.file;if(!fs.existsSync(file))continue;const html=fs.readFileSync(file,'utf8');const main=html.match(/<main[^>]*>([\s\S]*?)<\/main>/)?.[1]||'';full.push('## '+p.route,'',plain(main).slice(0,12000),'');}
write('dist/llms-full.txt',full.join('\n'));
console.log('Audit architecture generated:',finalPages.length,'pages. Hosting: Cloudflare Pages adapter; mode:',production?'production (indexable, _redirects active)':'preview (noindex, no _redirects)');
