// Cloudflare Pages adapter: files that only make sense for the hosting platform.
//   dist/_headers   security + cache headers, noindex on *.pages.dev and on preview builds
//   dist/_redirects legacy-URL 301s (production only; written by audit.mjs, validated here)
//   dist/robots.txt environment-dependent
//   functions/_shared/lead-procedures.js  allow-list used by the /api/lead Pages Function
import fs from 'node:fs';
import {robotsTxt} from './site-env.mjs';
const origin=JSON.parse(fs.readFileSync('config.json','utf8')).origin;
export function writeCloudflareAdapter(production){
 const common=['  X-Content-Type-Options: nosniff','  Referrer-Policy: strict-origin-when-cross-origin','  Permissions-Policy: camera=(), microphone=(), geolocation=()','  X-Frame-Options: SAMEORIGIN'];
 const headers=[
  '# Generated by build (cloudflare.mjs). Cloudflare Pages _headers format.',
  '/*',...common,...(production?[]:['  X-Robots-Tag: noindex, nofollow']),
  // Deployment aliases on pages.dev must never compete with https://fulviocorrea.com.co.
  'https://:project.pages.dev/*','  X-Robots-Tag: noindex, nofollow',
  'https://:version.:project.pages.dev/*','  X-Robots-Tag: noindex, nofollow',
  '/assets/*','  Cache-Control: public, max-age=604800',
  '/config.js','  Cache-Control: public, max-age=300',
  ''].join('\n');
 fs.writeFileSync('dist/_headers',headers);
 fs.writeFileSync('dist/robots.txt',robotsTxt(production,origin));
 // _redirects: 2,000 static + 100 dynamic rules, 1,000 chars per rule.
 // Classification is order-dependent (workers-sdk #14694): the first source with
 // * or :name makes every following line dynamic, and Cloudflare silently drops
 // the file once the dynamic count passes 100. Exact rules after a splat fail
 // the build even when the count is still under 100.
 if(production){
  const lines=fs.readFileSync('dist/_redirects','utf8').split('\n').filter(l=>l.trim()&&!l.startsWith('#'));
  const errors=[];
  let dynamicMode=false,staticCount=0,dynamicCount=0,firstDropped=null,staticAfterDynamic=null;
  for(const l of lines){
   const [from,to,code,...rest]=l.split(/\s+/);
   if(!from?.startsWith('/')||!to||!/^30[12378]$/.test(code||'')||rest.length||l.length>1000){errors.push('invalid rule: '+l);continue;}
   const splat=/[*:]/.test(from);
   if(dynamicMode&&!splat&&!staticAfterDynamic)staticAfterDynamic=l;
   if(splat)dynamicMode=true;
   if(dynamicMode){dynamicCount++;if(dynamicCount>100&&!firstDropped)firstDropped=l;}
   else staticCount++;
  }
  if(staticCount>2000)errors.push('more than 2,000 static redirects');
  if(staticAfterDynamic)errors.push('exact redirect after a splat or placeholder (Cloudflare counts it as dynamic and may drop the tail): '+staticAfterDynamic);
  if(dynamicCount>100)errors.push('more than 100 dynamic redirects; first dropped: '+firstDropped);
  if(errors.length)throw Error('dist/_redirects is not valid for Cloudflare Pages:\n'+errors.join('\n'));
 }else if(fs.existsSync('dist/_redirects'))throw Error('Preview builds must not publish _redirects.');
 // Allow-list for the lead Function (bundled by Cloudflare from functions/, no fs at runtime).
 const procedures=fs.readdirSync('content/procedures').filter(f=>f.endsWith('.en.json')).map(f=>JSON.parse(fs.readFileSync('content/procedures/'+f,'utf8'))).filter(p=>p.offeredConfirmed).map(p=>p.slug).sort();
 const mod='// Generated by `npm run build` from content/procedures/*.en.json (offeredConfirmed). Do not edit.\nexport default '+JSON.stringify(procedures)+';\n';
 fs.mkdirSync('functions/_shared',{recursive:true});
 if(!fs.existsSync('functions/_shared/lead-procedures.js')||fs.readFileSync('functions/_shared/lead-procedures.js','utf8')!==mod)fs.writeFileSync('functions/_shared/lead-procedures.js',mod);
}
