import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync('phone-country.js','utf8')+'\n'+fs.readFileSync('contact-widget.js','utf8');
const countries=JSON.parse(fs.readFileSync('data/phone-countries.json'));
let uuidCount=0;
function setup({endpoint='',response=200,accepted=true,consent='denied',locales=['en-US']}={}){
 const nodes=new Map(),requests=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,dataset:{},listeners:{},setAttribute(){},setCustomValidity(v){this.validation=v;},addEventListener(k,fn){this.listeners[k]=fn;},after(){},focus(){},select(){},showModal(){},close(){}});return nodes.get(id);};
 const country=node('contact-country');country.options=countries.map(c=>({value:c.iso,selected:c.iso==='CO',textContent:new Intl.DisplayNames(['es'],{type:'region'}).of(c.iso)+' (+'+c.code+')',dataset:{rule:JSON.stringify(c)}}));country.replaceChildren=(...items)=>{country.options=items;};
 const elements=Object.fromEntries(['name','phone','procedure','website'].map(k=>[k,node(k)]));Object.assign(elements.name,{value:'Test Person'});elements.phone.value='+1 202 555 0100';Object.assign(elements.procedure,{value:'other',selectedIndex:0,options:[{textContent:'Other'}]});
 const form=node('contact-intake');form.elements=elements;form.reportValidity=()=>!elements.name.validation&&!elements.phone.validation;
 const links=['whatsapp','instagram','sms','facebook'].map(k=>{const n=node('contact-'+k);n.dataset.contactChannel=k;return n;});
 const storage={fc_consent:JSON.stringify(consent),fc_attribution:JSON.stringify({first_touch:{landing_page:'https://practice.test/en/',referrer:'https://source.test/',utm_source:'first'},last_touch:{utm_source:'google',gclid:'test-click',gbraid:'braid',wbraid:'wbraid'}})};
 const callForm=node('contact-call-form');callForm.checked={value:'morning',nextElementSibling:{textContent:'Morning (8 am – 12 pm)'}};callForm.querySelector=()=>callForm.checked;
 const context={window:{SITE_CONFIG:{leadEndpoint:endpoint,contactChannels:{whatsapp:'16506656265',sms:'+16506656265'}}},document:{documentElement:{lang:'en'},body:{classList:{add(){},remove(){}}},referrer:'',getElementById:node,createElement:()=>node("thanks"),querySelector:()=>null,querySelectorAll:selector=>selector==="[data-open-contact]"?[]:links},sessionStorage:{getItem:k=>storage[k]||null},localStorage:{getItem:k=>k==='fc_journey'?'{"v":2,"f":1,"p":[["/en/","Home",2]]}':null},navigator:{userAgent:'test',languages:locales},location:new URL('https://practice.test/en/?secret=excluded'),URL,AbortController,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'test-lead-'+(++uuidCount)},fetch:async(url,options)=>{requests.push({url,...options,body:JSON.parse(options.body)});return{ok:response===200,text:async()=>JSON.stringify({accepted})};}};
 vm.runInNewContext(source,context);return {node,form,elements,requests,context,submit:()=>form.onsubmit({preventDefault(){}}),choose:id=>node('contact-'+id).listeners.click({preventDefault(){}})};
}
let s=setup();s.submit();assert.equal(s.requests.length,0);assert.equal(s.node('contact-channels').hidden,false);assert.match(decodeURIComponent(s.node('contact-whatsapp').href),/Test Person.*\+12025550100.*Other/);s.choose('instagram');await new Promise(r=>setImmediate(r));assert.equal(s.requests.length,0,'No endpoint means no network');assert.equal(s.context.window.dataLayer,undefined,'No optional measurement without consent');
s=setup();s.elements.phone.value='555';s.submit();assert.ok(s.elements.phone.validation);assert.equal(s.node('contact-whatsapp').href,undefined);s=setup();s.elements.website.value='spam';s.submit();assert.equal(s.node('contact-whatsapp').href,undefined,'Honeypot must block progress');
// Lead capture: "Choose how to connect" posts lead_created; each channel posts channel_selected with the same lead_id.
const flush=()=>new Promise(r=>setImmediate(r));
s=setup({endpoint:'/api/lead',consent:'granted'});s.node('contact-open').dataset.cta='contact-widget-open';s.node('contact-open').onclick();s.form.listeners.input();s.submit();assert.equal(s.requests.length,1,'lead_created on "Choose how to connect"');
let created=s.requests[0];assert.equal(created.url,'/api/lead');assert.equal(created.method,'POST');assert.equal(created.keepalive,true);assert.equal(created.body.event,'lead_created');assert.equal(created.headers['Idempotency-Key'],created.body.event_id);
for(const [k,v] of Object.entries({name:'Test Person',phone:'+12025550100',phone_country:'US',procedure:'other',language:'en',contact_consent:true,contact_preference:'pending',utm_source:'google',utm_source_first:'first',gclid:'test-click',gclid_last:'test-click',landing_page:'https://practice.test/en/',page_url:'https://practice.test/en/',form_id:'contact-widget'}))assert.deepEqual(created.body[k],v,'lead_created.'+k);
assert.ok(created.body.lead_id&&created.body.timezone!==undefined&&created.body.client_timestamp,'lead id, timezone and timestamp');assert.equal(created.body.journey,'{"v":2,"f":1,"p":[["/en/","Home",2]]}','site journey (fc_journey) travels with the lead');assert.ok(!created.body.page_url.includes('secret'),'no arbitrary query string');
assert.equal(s.node('contact-channels').hidden,false,'channels shown without waiting for the request');await flush();
s.choose('whatsapp');assert.equal(s.requests.length,2);let chosen=s.requests[1].body;assert.equal(chosen.event,'channel_selected');assert.equal(chosen.channel,'whatsapp');assert.equal(chosen.lead_id,created.body.lead_id);assert.equal(chosen.phone,'+12025550100');assert.notEqual(chosen.event_id,created.body.event_id);assert.match(decodeURIComponent(s.node('contact-whatsapp').href),/Test Person.*\+12025550100.*Other/);
s.choose('whatsapp');assert.equal(s.requests.length,2,'a channel is recorded once per lead');for(const channel of ['sms','instagram','facebook'])s.choose(channel);assert.equal(s.requests.length,5);assert.match(decodeURIComponent(s.node('contact-sms').href),/Test Person.*Other/);
s.node('contact-call').listeners.click();assert.equal(s.node('contact-call-form').hidden,false,'call form revealed');s.node('contact-call-form').onsubmit({preventDefault(){}});assert.equal(s.requests.length,6);
chosen=s.requests[5].body;assert.equal(chosen.channel,'call');assert.equal(chosen.contact_preference,'call');assert.equal(chosen.preferred_call_time,'morning');assert.equal(chosen.lead_id,created.body.lead_id);await flush();await flush();
assert.equal(s.node('contact-call-done').hidden,false);assert.match(s.node('contact-call-done').textContent,/Our team will call you at \+12025550100, morning/);
const events=s.context.window.dataLayer.map(e=>e.event);for(const e of ['form_start','generate_lead','contact_channel_selected','whatsapp_click','sofia_open','lead_submit'])assert.ok(events.includes(e),'dataLayer '+e);
assert.equal(s.context.window.dataLayer.find(e=>e.event==='generate_lead').procedure,'other');assert.ok(s.context.window.dataLayer.some(e=>e.event==='contact_channel_selected'&&e.channel==='call'));
const opened=s.context.window.dataLayer.find(e=>e.event==='sofia_open');assert.equal(opened.link_location,'contact-widget-open');assert.equal(opened.page_lang,'en');
const wa=s.context.window.dataLayer.find(e=>e.event==='whatsapp_click');assert.equal(wa.procedure,'other');assert.equal(wa.page_lang,'en');assert.equal(wa.link_location,'contact-widget');
const leads=s.context.window.dataLayer.filter(e=>e.event==='lead_submit');
assert.ok(leads.some(e=>e.contact_preference==='pending'&&e.procedure==='other'&&e.page_lang==='en'));
assert.ok(leads.some(e=>e.contact_preference==='whatsapp'&&e.procedure==='other'&&!e.name&&!e.phone&&!e.email));
assert.ok(leads.some(e=>e.contact_preference==='call'&&e.procedure==='other'));
assert.ok(!JSON.stringify(s.context.window.dataLayer).includes('Test Person'));assert.ok(!JSON.stringify(s.context.window.dataLayer).includes('12025550100'));
s.submit();assert.equal(s.requests.length,6,'unchanged details keep the same lead');s.elements.name.value='Other Person';s.submit();assert.equal(s.requests.length,7);assert.notEqual(s.requests[6].body.lead_id,created.body.lead_id,'edited details create a new lead');
s=setup({endpoint:'/api/lead',response:503,accepted:false});s.submit();s.node('contact-call').listeners.click();s.node('contact-call-form').onsubmit({preventDefault(){}});await flush();await flush();assert.equal(s.node('contact-call-done').hidden,true,'no confirmation when the request fails');assert.match(s.node('contact-status').textContent,/could not send/);assert.equal(s.context.window.dataLayer,undefined,'no events without consent');
console.log('PASS: widget validation, honeypot, lead_created on "Choose how to connect", channel_selected per channel (same lead_id/phone), call request with time window and confirmation, failure message, consent-gated PII-free dataLayer.');
let phoneTest=setup({locales:['es-CO']});assert.equal(phoneTest.node('contact-country').value,'CO');assert.equal(phoneTest.context.window.FCPhone.read('300 123 4567').number,'+573001234567');assert.equal(phoneTest.context.window.FCPhone.read('+1 2025550100'),null);
for(const [iso,input,expected] of [['GB','020 7946 0018','+442079460018'],['IT','02 3661 8300','+390236618300'],['US','202-555-0100','+12025550100']]){phoneTest.node('contact-country').value=iso;phoneTest.node('contact-country').onchange();assert.equal(phoneTest.context.window.FCPhone.read(input).number,expected);}
phoneTest=setup({locales:['en']});assert.equal(phoneTest.node('contact-country').value,'CO');phoneTest.node('contact-country-search').value='espana';phoneTest.node('contact-country-search').oninput();assert.equal(phoneTest.node('contact-country').options[0].value,'ES');phoneTest.node('contact-country-search').value='+1';phoneTest.node('contact-country-search').oninput();assert.ok(phoneTest.node('contact-country').options.some(x=>x.value==='CA'));assert.ok(phoneTest.node('contact-country').options.some(x=>x.value==='US'));console.log('Country tests passed: locale, fallback, search, shared codes, UK trunk prefix, Italian significant zero, international paste and CRM normalization.');
