/* Lightweight channel handoff; personal data stays in memory until a channel is chosen. */
(()=>{'use strict';if(typeof document==='undefined')return;
 const dialog=document.getElementById('contact-dialog');if(!dialog)return;
 const config=window.SITE_CONFIG||{},channels=config.contactChannels||{},lang=document.documentElement.lang==='es'?'es':'en',t=(en,es)=>lang==='es'?es:en;
 const open=document.getElementById('contact-open'),form=document.getElementById('contact-intake'),panel=document.getElementById('contact-channels'),status=document.getElementById('contact-status');
 let contact=null;
 const read=key=>{try{return JSON.parse(sessionStorage.getItem(key));}catch{return null;}};
 const measure=channel=>{if(read('fc_consent')!=='granted')return;const detail={channel,cta_id:'contact-'+channel,language:lang,page_path:location.pathname};window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'contact_channel_click',...detail});if(channel==='whatsapp')window.dataLayer.push({event:'whatsapp_click',...detail});if(config.ga4Id&&!config.gtmId){function gtag(){window.dataLayer.push(arguments);}gtag('event','contact_channel_click',detail);if(channel==='whatsapp')gtag('event','whatsapp_click',detail);}};
 let opener=open;
 const showContact=(trigger)=>{opener=trigger;const procedure=trigger.dataset.procedure;if(procedure&&[...form.elements.procedure.options].some(o=>o.value===procedure)){form.elements.procedure.value=procedure;form.hidden=false;panel.hidden=true;}document.querySelector('.nav')?.classList.remove('open');document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');dialog.showModal();open.setAttribute('aria-expanded','true');document.body.classList.add('contact-is-open');(form.hidden?document.getElementById('contact-channel-title'):form.elements.name).focus();};
 open.onclick=()=>showContact(open);
 document.querySelectorAll('[data-open-contact]').forEach(button=>button.addEventListener('click',()=>showContact(button)));
 document.getElementById('contact-close').onclick=()=>dialog.close();
 dialog.addEventListener('close',()=>{open.setAttribute('aria-expanded','false');document.body.classList.remove('contact-is-open');opener.focus();});
 form.elements.phone.setAttribute('aria-describedby','contact-phone-help');
 form.elements.phone.oninput=()=>form.elements.phone.setCustomValidity('');
 form.onsubmit=e=>{e.preventDefault();if(form.elements.website.value)return;
  const name=form.elements.name.value.trim(),parsed=window.FCPhone?.read(form.elements.phone.value),phone=parsed?.number||'';
  form.elements.name.setCustomValidity(name?'':t('Enter your name.','Escribe tu nombre.'));
  form.elements.phone.setCustomValidity(parsed?'':t('Check the selected country and enter your full phone number.','Revisa el país seleccionado y escribe tu número completo.'));
  if(!form.reportValidity())return;
  const selected=form.elements.procedure,procedure=selected.options[selected.selectedIndex].textContent;
  const next={name,phone,phone_country:parsed.country,phone_country_code:parsed.dial,procedure:selected.value,procedure_label:procedure,contact_consent:true,sms_consent:form.elements.sms_consent?.checked||false,language:lang};
  contact=next;
  const message=t(`Hello Sofía, my name is ${name}. My phone number is ${phone}. I am interested in ${procedure}.`,`Hola Sofía, me llamo ${name}. Mi teléfono es ${phone}. Me interesa ${procedure}.`)+` [ref: ${selected.value}-${lang}]`;
  const whatsapp=document.getElementById('contact-whatsapp');if(whatsapp)whatsapp.href='https://wa.me/'+channels.whatsapp+'?text='+encodeURIComponent(message);
  const sms=document.getElementById('contact-sms');if(sms)sms.href='sms:'+channels.sms+(/iPad|iPhone|iPod/.test(navigator.userAgent)?'&':'?')+'body='+encodeURIComponent(message);
  form.hidden=true;panel.hidden=false;status.textContent='';document.getElementById('contact-channel-title').focus({preventScroll:true});dialog.scrollTop=0;
 };
 form.elements.name.oninput=()=>form.elements.name.setCustomValidity('');
 document.getElementById('contact-back').onclick=()=>{panel.hidden=true;form.hidden=false;status.textContent='';form.elements.name.focus();};
 document.querySelectorAll('[data-contact-channel]').forEach(a=>a.addEventListener('click',e=>{if(!contact){e.preventDefault();return;}measure(a.dataset.contactChannel);status.textContent=t('Complete and send your message in the selected app.','Completa y envía tu mensaje en la aplicación elegida.');}));
})();
