import fs from 'node:fs';
const phoneCountries=JSON.parse(fs.readFileSync('data/phone-countries.json','utf8'));
import {esc} from './editorial.mjs';
export function contactWidget(lang,procedures,channels){
 const es=lang==='es',t=(en,esText)=>es?esText:en;
 const names=new Intl.DisplayNames([lang],{type:'region'});const countries=phoneCountries.map(c=>({...c,label:names.of(c.iso)})).sort((a,b)=>a.label.localeCompare(b.label,lang));
 const chatIcon='<svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2v-10A9.5 9.5 0 0 1 11.5 2 9.5 9.5 0 0 1 21 11.5Z"/><path d="M7 9h10M7 13h7"/></svg>';
 return `<div class="contact-launcher"><button type="button" id="contact-open" aria-haspopup="dialog" aria-controls="contact-dialog" aria-expanded="false" data-cta="contact-widget-open">${chatIcon}<span>${t('Talk to Sofía','Habla con Sofía')}</span></button></div>
 <dialog id="contact-dialog" class="contact-dialog" aria-labelledby="contact-title"><div class="contact-heading"><div class="contact-avatar" aria-hidden="true">S</div><div><p id="contact-title">Sofía</p><span>${t('Patient care team','Equipo de atención al paciente')}</span></div><button type="button" id="contact-close" aria-label="${t('Close contact window','Cerrar ventana de contacto')}">×</button></div>
 <div class="contact-content"><form id="contact-intake" data-form="contact-widget"><p class="contact-greeting">${t('Hello! Welcome to Dr. Fulvio Correa’s practice. How can we help you?','¡Hola! Bienvenido al consultorio del Dr. Fulvio Correa. ¿Cómo podemos ayudarte?')}</p><p class="contact-intro">${t('Tell us a little about yourself, then choose where to start your conversation with Sofía.','Cuéntanos un poco sobre ti y elige dónde iniciar tu conversación con Sofía.')}</p>
 <label for="contact-name">${t('Your name','Tu nombre')}</label><input id="contact-name" name="name" autocomplete="name" maxlength="100" required>
 <div class="contact-phone-row"><div><label for="contact-country-toggle">${t('Country / code','País / código')}</label><details id="contact-country-picker"><summary id="contact-country-toggle">Colombia (+57)</summary><div class="country-options"><label for="contact-country-search">${t('Find country or code','Buscar país o código')}</label><input id="contact-country-search" type="search" placeholder="${t('Search…','Buscar…')}" autocomplete="off"><select id="contact-country" name="phone_country" size="6" aria-label="${t('Country calling code','Código telefónico de país')}">${countries.map(c=>`<option value="${c.iso}" data-code="${c.code}" data-rule="${esc(JSON.stringify(c))}" ${c.iso==='CO'?'selected':''}>${esc(c.label)} (+${c.code})</option>`).join('')}</select><p id="country-empty" hidden>${t('No countries found','No se encontraron países')}</p></div></details></div><div><label for="contact-phone">${t('Phone number','Número de teléfono')}</label><input id="contact-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel-national" maxlength="25" required></div></div><p id="contact-phone-help" class="contact-hint">${t('Enter your number without the country code.','Escribe tu número sin el código de país.')}</p>
 <label for="contact-procedure">${t('Procedure of interest','Procedimiento de interés')}</label><select id="contact-procedure" name="procedure" required><option value="">${t('Select a procedure','Selecciona un procedimiento')}</option>${procedures.filter(p=>p.lang===lang&&p.offeredConfirmed).map(p=>`<option value="${esc(p.slug)}">${esc(p.name)}</option>`).join('')}<option value="other">${t('Other','Otro')}</option></select>
 <div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div>
 <label class="contact-consent"><input type="checkbox" name="contact_consent" required><span>${t('I agree to be contacted about this enquiry and have read the','Acepto que me contacten sobre esta solicitud y he leído la')} <a href="/${lang}/privacy/">${t('privacy policy','política de privacidad')}</a>.</span></label>
 <button type="submit" class="contact-primary" id="contact-continue">${t('Choose how to connect','Elegir cómo contactar')} <span aria-hidden="true">→</span></button></form>
 <section id="contact-channels" hidden aria-labelledby="contact-channel-title"><button type="button" id="contact-back" class="contact-back">← ${t('Edit my details','Editar mis datos')}</button><h2 id="contact-channel-title" tabindex="-1">${t('Where shall we talk?','¿Por dónde conversamos?')}</h2><p class="contact-intro">${t('Send your message in the app you choose to start the conversation.','Envía el mensaje en la aplicación que elijas para iniciar la conversación.')}</p>
 <div class="contact-channel-list">${[['whatsapp','WhatsApp','W'],['instagram','Instagram','◎'],['sms','SMS','✉'],['facebook','Facebook','f']].filter(([id])=>id==='whatsapp'||channels[id]).map(([id,label,icon])=>`<a id="contact-${id}" data-contact-channel="${id}" data-cta="contact-${id}" href="${esc(id==='whatsapp'?'https://wa.me/'+channels.whatsapp:id==='sms'?'sms:'+channels.sms:channels[id])}" ${id==='sms'?'':'target="_blank" rel="noopener noreferrer"'}><span class="channel-icon channel-${id}" aria-hidden="true">${icon}</span><span>${label}</span><span aria-hidden="true">↗</span></a>`).join('')}</div>
 </section>
 <p id="contact-status" class="contact-status" role="status" aria-live="polite"></p></div><p class="contact-footer">Dr. Fulvio Correa · Cartagena</p></dialog>`;
}
