import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const source=fs.readFileSync('phone-country.js','utf8')+'\n'+fs.readFileSync('contact-widget.js','utf8');
const countries=JSON.parse(fs.readFileSync('data/phone-countries.json'));
function setup({endpoint='',response=200,accepted=true,consent='denied',locales=['en-US']}={}){
 const nodes=new Map(),requests=[];const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,dataset:{},listeners:{},setAttribute(){},setCustomValidity(v){this.validation=v;},addEventListener(k,fn){this.listeners[k]=fn;},after(){},focus(){},select(){},showModal(){},close(){}});return nodes.get(id);};
 const country=node('contact-country');country.options=countries.map(c=>({value:c.iso,selected:c.iso==='CO',textContent:new Intl.DisplayNames(['es'],{type:'region'}).of(c.iso)+' (+'+c.code+')',dataset:{rule:JSON.stringify(c)}}));country.replaceChildren=(...items)=>{country.options=items;};
 const elements=Object.fromEntries(['name','phone','procedure','website'].map(k=>[k,node(k)]));Object.assign(elements.name,{value:'Test Person'});elements.phone.value='+1 202 555 0100';Object.assign(elements.procedure,{value:'other',selectedIndex:0,options:[{textContent:'Other'}]});
 const form=node('contact-intake');form.elements=elements;form.reportValidity=()=>!elements.name.validation&&!elements.phone.validation;
 const links=['whatsapp','instagram','sms','facebook'].map(k=>{const n=node('contact-'+k);n.dataset.contactChannel=k;return n;});
 const storage={fc_consent:JSON.stringify(consent),fc_attribution:JSON.stringify({first_touch:{landing_page:'https://practice.test/en/',referrer:'https://source.test/',utm_source:'first'},last_touch:{utm_source:'google',gclid:'test-click',gbraid:'braid',wbraid:'wbraid'}})};
 const context={window:{SITE_CONFIG:{leadEndpoint:endpoint,contactChannels:{whatsapp:'16506656265',sms:'+16506656265'}}},document:{documentElement:{lang:'en'},body:{classList:{add(){},remove(){}}},referrer:'',getElementById:node,createElement:()=>node("thanks"),querySelector:()=>null,querySelectorAll:selector=>selector==="[data-open-contact]"?[]:links},sessionStorage:{getItem:k=>storage[k]||null},navigator:{userAgent:'test',languages:locales},location:new URL('https://practice.test/en/?secret=excluded'),URL,AbortController,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'test-lead'},fetch:async(url,options)=>{requests.push({url,...options});return{ok:response===200,text:async()=>JSON.stringify({accepted})};}};
 vm.runInNewContext(source,context);return {node,form,elements,requests,context,submit:()=>form.onsubmit({preventDefault(){}}),choose:id=>node('contact-'+id).listeners.click({preventDefault(){}})};
}
let s=setup();s.submit();assert.equal(s.requests.length,0);assert.equal(s.node('contact-channels').hidden,false);assert.match(decodeURIComponent(s.node('contact-whatsapp').href),/Test Person.*\+12025550100.*Other/);s.choose('instagram');await new Promise(r=>setImmediate(r));assert.equal(s.requests.length,0,'No endpoint means no network');assert.equal(s.context.window.dataLayer,undefined,'No optional measurement without consent');
s=setup();s.elements.phone.value='555';s.submit();assert.ok(s.elements.phone.validation);assert.equal(s.node('contact-whatsapp').href,undefined);s=setup();s.elements.website.value='spam';s.submit();assert.equal(s.node('contact-whatsapp').href,undefined,'Honeypot must block progress');
s=setup({endpoint:'https://crm.test/lead',consent:'granted'});s.submit();for(const channel of ['whatsapp','sms','instagram','facebook'])s.choose(channel);await new Promise(r=>setImmediate(r));assert.equal(s.requests.length,0,'Widget must never create leads, even with an endpoint configured');assert.ok(!JSON.stringify(s.context.window.dataLayer).includes('Test Person'));assert.ok(!JSON.stringify(s.context.window.dataLayer).includes('12025550100'));assert.match(decodeURIComponent(s.node('contact-sms').href),/Test Person.*Other/);console.log('PASS: messaging-only widget, no CRM requests, name and procedure handoff, validation, honeypot and consent-gated anonymous events.');
let phoneTest=setup({locales:['es-CO']});assert.equal(phoneTest.node('contact-country').value,'CO');assert.equal(phoneTest.context.window.FCPhone.read('300 123 4567').number,'+573001234567');assert.equal(phoneTest.context.window.FCPhone.read('+1 2025550100'),null);
for(const [iso,input,expected] of [['GB','020 7946 0018','+442079460018'],['IT','02 3661 8300','+390236618300'],['US','202-555-0100','+12025550100']]){phoneTest.node('contact-country').value=iso;phoneTest.node('contact-country').onchange();assert.equal(phoneTest.context.window.FCPhone.read(input).number,expected);}
phoneTest=setup({locales:['en']});assert.equal(phoneTest.node('contact-country').value,'CO');phoneTest.node('contact-country-search').value='espana';phoneTest.node('contact-country-search').oninput();assert.equal(phoneTest.node('contact-country').options[0].value,'ES');phoneTest.node('contact-country-search').value='+1';phoneTest.node('contact-country-search').oninput();assert.ok(phoneTest.node('contact-country').options.some(x=>x.value==='CA'));assert.ok(phoneTest.node('contact-country').options.some(x=>x.value==='US'));console.log('Country tests passed: locale, fallback, search, shared codes, UK trunk prefix, Italian significant zero, international paste and CRM normalization.');
