import {physicianNode,membershipView} from './practice-view.mjs';
import {resultsViews} from './results-view.mjs';
import {contactWidget} from './contact-widget.mjs';
import fs from 'node:fs';
import {imageMeta} from './assets.mjs';
import {robotsTxt} from './site-env.mjs';
import {posts,read,esc,markdown,write} from './editorial.mjs';
const cfg=read('config.json'),practice=read('data/practice.json'),images=imageMeta(),categories=read('data/categories.json'),results=read('data/results.json');
const contactChannels={...read('data/contact-channels.json'),whatsapp:practice.whatsapp};
const origin=cfg.origin,production=process.env.SITE_ENV==='production',allPosts=posts(),published=allPosts.filter(p=>!p.draft),procedures=fs.readdirSync('content/procedures').map(f=>read('content/procedures/'+f));
const manifest=new Map(read('pages.json').map(p=>[p.route,p]));
const templates=Object.fromEntries(['en','es'].map(l=>[l,fs.readFileSync('dist/'+l+'/about/index.html','utf8')]));
const pick=(l,en,es)=>l==='en'?en:es;
const image=(file,alt='',eager=false)=>{const m=images[file];if(!m)throw Error('Unknown image '+file);return `<img src="/assets/${file}" ${images[file.replace('.webp','-600.webp')]?`srcset="/assets/${file.replace('.webp','-600.webp')} 600w, /assets/${file} 1200w" sizes="(max-width: 650px) 88vw, (max-width: 1000px) 44vw, 30vw"`:''} alt="${esc(alt)}" width="${m.width}" height="${m.height}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;};
const wa=(l,p='')=>'https://wa.me/'+practice.whatsapp+'?text='+encodeURIComponent(pick(l,'Hello, I would like information about ','Hola, quisiera información sobre ')+(p||pick(l,'a consultation with Dr. Fulvio Correa.','una valoración con el Dr. Fulvio Correa.')));
const waLink=(l,id,p='')=>`<a class="textlink" id="${id}" data-cta="${id}" data-event="whatsapp_click" href="${wa(l,p)}" target="_blank" rel="noopener">WhatsApp ${id==='header-whatsapp'?practice.messagingDisplay:''} ↗</a>`;
const author=l=>`<aside class="author-block">${image('doctor.webp',practice.name)}<div><a href="/${l}/about/">${esc(practice.name)}</a><p>Cartagena de Indias · Colombia</p></div></aside>`;
const cards=(items,l)=>`<div class="blog-grid">${items.map(p=>`<a class="blog-card" href="/${p.lang}/blog/${p.slug}/">${image(p.cover.replace('/assets/',''),p.coverAlt)}<p class="eyebrow">${esc(categories.find(c=>c.en===p.category)?.[l]||p.category)}</p><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><span class="textlink">${pick(l,'Read article','Leer artículo')} ↗</span></a>`).join('')}</div>`;
const intro=(l,label,title,description)=>`<section class="page-hero wrap"><p class="eyebrow">${esc(label)}</p><h1>${esc(title)}</h1><p class="lead">${esc(description)}</p></section>`;
function make(l,slug,title,description,body,options={}){const route=`/${l}/${slug}`,file='dist'+route+'index.html';let html=templates[l].replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)} | Dr. Fulvio Correa</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(description)}">`).replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${body}</main>`);write(file,html);manifest.set(route,{route,file,lang:l,ads:false,noindex:!!options.noindex,updated:options.updated||'2026-09-25',schemas:options.schemas||[],alternate:options.alternate,cover:options.cover});}
for(const l of ['en','es']){
 const local=published.filter(p=>p.lang===l).sort((a,b)=>b.date.localeCompare(a.date));
 make(l,'blog/',pick(l,'Journal & patient resources','Blog y recursos para pacientes'),pick(l,'Explore plastic surgery, recovery and travel to Cartagena through articles from the practice. Find procedure guides and questions for your consultation.','Explora artículos sobre cirugía plástica, recuperación y viajes a Cartagena. Consulta guías por procedimiento y prepara tus preguntas para la valoración.'),intro(l,'Journal',pick(l,'Thoughtful guidance.','Información para decidir.'),pick(l,'Perspectives on surgery, recovery and your journey to Cartagena.','Cirugía, recuperación y tu viaje a Cartagena.'))+`<section class="section wrap no-top"><nav class="category-nav" aria-label="${pick(l,'Categories','Categorías')}">${categories.map(c=>`<a href="/${l}/blog/category/${c.slug}/">${c[l]}</a>`).join('')}</nav>${cards(local,l)}</section>`);
 for(const c of categories){const selected=local.filter(p=>p.category===c.en);make(l,`blog/category/${c.slug}/`,c[l],pick(l,`Explore ${c.en.toLowerCase()} articles, patient questions and preparation resources for an individual consultation with the practice in Cartagena, Colombia.`,`Explora artículos de ${c.es.toLowerCase()}, preguntas de pacientes y recursos para preparar tu valoración individual con el consultorio en Cartagena, Colombia.`),intro(l,'Journal',c[l],pick(l,'Patient information and perspectives.','Información y perspectivas para pacientes.'))+`<section class="section wrap no-top">${selected.length?cards(selected,l):`<p>${pick(l,'Explore the journal for related patient resources.','Explora el blog para consultar recursos relacionados.')}</p>`}<a class="textlink" href="/${l}/blog/">${pick(l,'All articles','Todos los artículos')} ↗</a></section>`,{noindex:!selected.length});}
 for(const p of local){const twin=published.find(x=>x.lang!==l&&x.slug===p.translationOf);const related=local.filter(x=>x.slug!==p.slug&&x.category===p.category).slice(0,3);make(l,`blog/${p.slug}/`,p.title,p.description,intro(l,categories.find(c=>c.en===p.category)?.[l]||p.category,p.title,p.description)+`<article class="article article-body wrap"><p class="post-dates">${pick(l,'Published','Publicado')}: <time datetime="${p.date}">${p.date}</time> · ${pick(l,'Updated','Actualizado')}: <time datetime="${p.updated}">${p.updated}</time></p>${author(l)}${image(p.cover.replace('/assets/',''),p.coverAlt)}${markdown(p.body)}${p.sources.length?`<section class="sources"><h2>${pick(l,'Sources','Fuentes')}</h2><ul>${p.sources.map(s=>`<li><a href="${esc(s)}" rel="noopener">${esc(new URL(s).hostname)} ↗</a></li>`).join('')}</ul></section>`:''}<p class="note">${pick(l,'General information does not replace an individual medical evaluation. Results and recovery vary.','La información general no sustituye una evaluación médica individual. Los resultados y la recuperación varían.')}</p>${twin?`<a class="textlink" href="/${twin.lang}/blog/${twin.slug}/" data-language="${twin.lang}">${pick(l,'Leer en español','Read in English')} ↗</a>`:''}</article><section class="section wrap"><h2>${pick(l,'Continue reading','Sigue leyendo')}</h2>${cards(related,l)}<a href="/${l}/blog/">${pick(l,'All articles','Todos los artículos')}</a></section>`,{updated:p.updated,cover:p.cover,alternate:twin?`/${twin.lang}/blog/${twin.slug}/`:null,schemas:[{'@context':'https://schema.org','@type':'BlogPosting',headline:p.title,description:p.description,datePublished:p.date,dateModified:p.updated,inLanguage:l,image:origin+p.cover,mainEntityOfPage:origin+`/${l}/blog/${p.slug}/`,author:{'@type':'Person',name:practice.name,url:origin+`/${l}/about/`},publisher:{'@id':origin+'/#physician'}}]});}
 for(const name of ['privacy','terms','sms']){const f=`content/legal/${name}.${l}.json`;if(fs.existsSync(f)){const doc=read(f);make(l,`${name}/`,doc.title,pick(l,`Read the practice's ${doc.title.toLowerCase()} and information about communication, website use and your relationship with the patient support team in Cartagena.`,`Consulta ${doc.title.toLowerCase()} e información sobre comunicaciones, uso del sitio y tu relación con el equipo de atención del consultorio en Cartagena.`),intro(l,pick(l,'Practice information','Información del consultorio'),doc.title,'')+`<article class="article article-body wrap">${markdown(doc.body)}</article>`);}}
 const rv=resultsViews(l,results,image);
 make(l,'before-after/',pick(l,'Before & after','Antes y después'),pick(l,'Explore how to assess before-and-after photographs and discuss individual results, recovery and realistic expectations with Dr. Fulvio Correa in Cartagena.','Conoce cómo valorar fotografías de antes y después y conversa sobre resultados individuales, recuperación y expectativas con el Dr. Fulvio Correa en Cartagena.'),rv.gallery,{noindex:!rv.hasCases});
}
const mapped={'/plastic-surgery-colombia':'/en/','/plastic-surgery-colombia-cartagena-mommy-makeover':'/en/procedures/mommy-makeover/','/plastic-surgery-colombia-cartagena-liposuction':'/en/procedures/liposuction/','/plastic-surgery-colombia-cartagena-facelift':'/en/procedures/facelift/','/draft-travel-es':'/es/international-patients/','/blog':'/en/blog/'};
for(const p of published)mapped['/post/'+p.slug]=`/${p.lang}/blog/${p.slug}/`;
write('migration/redirects.json',JSON.stringify({active:false,root:'browser-language-detection',redirects:Object.entries(mapped).map(([from,to])=>({from,to,status:301}))},null,2));
write('migration/_redirects.pending',Object.entries(mapped).map(([a,b])=>`${a} ${b} 301`).join('\n'));
function pillars(l){const groups=[{id:'face',en:'Facial Refinement',es:'Armonía facial',image:'84-home-1-8.webp',slugs:['facelift','rhinoplasty']},{id:'body',en:'Sculpted Silhouette',es:'Contorno corporal',image:'84-home-1-9.webp',slugs:['liposuction','mommy-makeover','tummy-tuck','bbl']},{id:'breast',en:'Breast Harmony',es:'Armonía mamaria',image:'official-670ff4e2c5bc5e344cbcc3fa.png.webp',slugs:['breast-lift-reduction','breast-augmentation']}];return `<section class="pillars section"><div class="wrap"><p class="eyebrow">${pick(l,'A personal approach','Una mirada personal')}</p><h2>${pick(l,'Core Treatment Pillars','Nuestros pilares de tratamiento')}</h2><div class="pillar-tabs" role="tablist" aria-label="${pick(l,'Treatment areas','Áreas de tratamiento')}">${groups.map((g,i)=>`<button role="tab" id="tab-${g.id}" aria-controls="pillar-${g.id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${g[l]}</button>`).join('')}</div>${groups.map((g,i)=>`<div class="pillar-panel" id="pillar-${g.id}" role="tabpanel" aria-labelledby="tab-${g.id}" ${i?'hidden':''}><div class="pillar-copy"><span class="eyebrow">0${i+1} / 03</span><h3>${g[l]}</h3><p>${pick(l,'An individual plan begins with your anatomy, your goals and a considered medical evaluation.','Un plan individual comienza con tu anatomía, tus objetivos y una valoración médica cuidadosa.')}</p>${g.slugs.map(s=>{const p=procedures.find(p=>p.slug===s&&p.lang===l);return p?`<a class="textlink" href="/${l}/procedures/${s}/">${esc(p.name)} ↗</a>`:'';}).join('')}</div><div class="pillar-photo">${image(g.image,g[l])}</div></div>`).join('')}</div></section>`;}
function credentials(l){return `<section class="credentials section wrap"><p class="eyebrow">${pick(l,'Education & training','Formación y trayectoria')}</p><h2>${pick(l,'Credentials You Can Trust','Formación que inspira confianza')}</h2><div class="credential-window" tabindex="0" aria-label="${pick(l,'Training carousel','Carrusel de formación')}"><div class="credential-track">${[0,1,2].map((n)=>practice.education.map(e=>`<div class="credential-card" ${n?'aria-hidden="true"':''}><span aria-hidden="true">✧</span><p>${esc(e[l])}</p></div>`).join('')).join('')}</div></div><button class="privacy-button" id="credential-pause" aria-pressed="false">${pick(l,'Pause animation','Pausar animación')}</button><p class="small-label">${pick(l,'Education as published in the official practice biography.','Formación publicada en la biografía oficial del consultorio.')} <a href="/${l}/about/">${pick(l,'Read biography','Leer biografía')} ↗</a></p></section>`;}
for(const p of manifest.values()){
 let html=fs.readFileSync(p.file,'utf8'),l=p.lang,other=l==='en'?'es':'en';
 html=html.replace(/<p class="preview-note">[\s\S]*?<\/p>/g,'').replace(/<a href="\/(en|es)\/image-sources\/">[^<]*<\/a>/g,'').replace(/<a href="\/(en|es)\/before-after\/">[^<]*<\/a>/g,'');
 html=html.replace(/https:\/\/fulviocorrea.com.co\/privacy-policy-1485/g,`/${l}/privacy/`).replace(/href="https:\/\/wa.link\/m7rk1q"/g,`href="${wa(l)}"`);
 html=html.replace(/<a class="sticky-mobile"[^>]*>[\s\S]*?<\/a>/,'');
 html=html.replace('<div class="language-picker"',`<a href="/${l}/blog/">Blog</a><div class="language-picker"`);
 html=html.replace('<button class="privacy-button" id="privacy-settings">',`<a href="/${l}/terms/">${pick(l,'Terms','Términos')}</a><a href="/${l}/sms/">SMS</a><button class="privacy-button" id="privacy-settings">`);
 if(practice.phone)html=html.replace('</nav></header>',`<a href="tel:${esc(practice.phone)}" id="header-phone" data-event="phone_click">${esc(practice.phoneDisplay||practice.phone)}</a></nav></header>`).replace('</footer>',`<a href="tel:${esc(practice.phone)}" id="footer-phone" data-event="phone_click">${esc(practice.phoneDisplay||practice.phone)}</a></footer>`);
 if(p.route===`/${l}/`){html=html.replace(/<section class="results section wrap">[\s\S]*?<\/section>/,'').replace(/<section class="philosophy section">[\s\S]*?<\/section>/,pillars(l)+credentials(l)+resultsViews(l,results,image).philosophy);}
 if(p.route===`/${l}/about/`)html=html.replace('</main>',resultsViews(l,results,image).philosophy+'</main>');
 html=html.replace('<div class="language-picker"',`<a href="/${l}/before-after/">${pick(l,'Before & after','Antes y después')}</a><div class="language-picker"`);
 if(p.route.includes('book-consultation')){html=html.replace(/<p class="note">[^<]*(?:preview|vista previa)[^<]*<\/p>/gi,'').replace(/(<button class="button" id="submit-consultation" type="submit">)[\s\S]*?(<span>)/,`$1${pick(l,'Request my consultation','Solicitar mi valoración')}$2`).replace('name="phone" type="tel"','name="phone" type="tel" placeholder="+1 555 123 4567" pattern="\\+[1-9][0-9 ()-]{6,24}"').replace('<label class="consent">',`<label>${pick(l,'Country','País')}<input name="country" autocomplete="country-name" maxlength="100" required></label><label>${pick(l,'Message','Mensaje')}<textarea name="message" maxlength="3000" rows="4"></textarea></label><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent">`);}
 if(p.route.includes('/faq/'))html=html.replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${pick(l,'Find answers about consultations, procedure planning, safety, recovery and traveling to Cartagena for a personal assessment with Dr. Fulvio Correa.','Resuelve dudas sobre valoración, planificación quirúrgica, seguridad, recuperación y viajes a Cartagena para una consulta personal con el Dr. Fulvio Correa.')}">`);
 // Every internal original URL is updated locally. Redirect files remain inactive.
 html=html.replace(/href="https:\/\/fulviocorrea.com.co([^"#?]*)([^\"]*)"/g,(whole,route,extra)=>mapped[route.replace(/\/$/,'')]?`href="${mapped[route.replace(/\/$/,'')]}${extra}"`:whole);
 html=html.replace(/<img\b[^>]*>/g,tag=>{const file=tag.match(/src="\/assets\/([^"]+)"/)?.[1],m=images[file];return m?tag.replace(/width="\d+"/,`width="${m.width}"`).replace(/height="\d+"/,`height="${m.height}"`):tag;});
 const counterpart=p.alternate===null?null:(p.alternate||p.route.replace(`/${l}/`,`/${other}/`));const alternates=[{lang:l,route:p.route},...(counterpart&&manifest.has(counterpart)?[{lang:other,route:counterpart}]:[])];const def=alternates.find(a=>a.lang==='en')||alternates[0];p.alternates=alternates;
 html=html.replace(/<link rel="(?:canonical|alternate)"[^>]*>/g,'').replace('</head>',`<link rel="canonical" href="${origin+p.route}">${alternates.map(a=>`<link rel="alternate" hreflang="${a.lang}" href="${origin+a.route}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin+def.route}"><meta property="og:image" content="${origin+(p.cover||'/assets/84-home-1-1.webp')}"><meta name="twitter:card" content="summary_large_image"></head>`).replace(/<meta property="og:url" content="[^"]*">/,`<meta property="og:url" content="${origin+p.route}">`);
 const title=html.match(/<title>(.*?)<\/title>/)?.[1]||practice.name,description=html.match(/<meta name="description" content="([^"]*)"/)?.[1]||'';html=html.replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${title}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${description}">`).replace(/<meta name="robots" content="[^"]*">/,`<meta name="robots" content="${production&&!p.ads&&!p.noindex?'index, follow':'noindex, nofollow'}">`);
 html=html.replace(/href="\/(en|es)\/about\/" data-language="(en|es)"/g,(m,target)=>`href="${target===l?p.route:counterpart||'/'+other+'/blog/'}" data-language="${target}"`);
 const physician=physicianNode(practice,origin);
 const previous=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)?.[1]||'[]');const schema=[physician,{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:pick(l,'Home','Inicio'),item:origin+`/${l}/`},{'@type':'ListItem',position:2,name:title.replace(/ &amp; /g,' & '),item:origin+p.route}]},...(p.schemas||previous.filter(s=>s['@type']==='FAQPage'))];html=html.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/,`<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`);
 // Distinct, full-width section surfaces; nested content keeps its own styling.
 const homeSurfaces=['photo','black','charcoal','plum','black','plum','charcoal','black','plum','charcoal','black','plum','charcoal','photo'];
 html=html.replace(/(<main id="main">)([\s\S]*?)(<\/main>)/,(all,start,body,end)=>{let depth=0,index=0;return start+body.replace(/<section\b[^>]*>|<\/section>/g,tag=>{if(tag.startsWith('</')){depth--;return tag;}const top=depth++===0;if(!top)return tag;const slot=index++;const surface=p.route===`/${l}/`?homeSurfaces[slot]||'black':/class="[^"]*(?:closing|ads-hero)/.test(tag)?'photo':/result-philosophy/.test(tag)?'plum':['charcoal','black','plum'][slot%3];return tag.replace('<section',`<section data-surface="${surface}"`);})+end;});
 html=html.replace('</body>',()=>contactWidget(l,procedures,contactChannels)+'</body>');
 write(p.file,html);
}
// Update language-entry documents from the final English pages, never stale preview text.
for(const p of manifest.values())if(p.lang==='en'){write('dist'+(p.route.slice(3)||'/')+'index.html',fs.readFileSync(p.file,'utf8').replace('<head>','<head><script src="/locale.js"></script>'));}
const runtime={origin,contactChannels:Object.fromEntries(['whatsapp','instagram','facebook','sms'].map(k=>[k,contactChannels[k]||''])),leadEndpoint:'/api/lead',gtmId:process.env.GTM_ID||'',ga4Id:process.env.GA4_ID||'',whatsapp:practice.whatsapp};
write('dist/config.js','window.SITE_CONFIG='+JSON.stringify(runtime)+';');
write('dist/robots.txt',robotsTxt(production,origin));
const indexable=[...manifest.values()].filter(p=>!p.ads&&!p.noindex);write('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+indexable.map(p=>`<url><loc>${origin+p.route}</loc><lastmod>${p.updated||'2026-09-25'}</lastmod>${p.alternates.map(a=>`<xhtml:link rel="alternate" hreflang="${a.lang}" href="${origin+a.route}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${origin+(p.alternates.find(a=>a.lang==='en')||p.alternates[0]).route}"/></url>`).join('')+'</urlset>');
write('dist/llms.txt',`# ${practice.name}\n\n> Plastic surgery practice in Cartagena de Indias, Colombia. Educational information does not replace individual medical assessment.\n\n${indexable.map(p=>`- [${p.route}](${origin+p.route})`).join('\n')}\n`);
write('pages.json',JSON.stringify([...manifest.values()],null,2));
console.log('Editorial pages:',manifest.size,'Published posts:',published.length,'Mode:',production?'production':'preview');
