// Tests the Cloudflare Pages Function (functions/api/lead.js) with a mocked HighLevel webhook:
// lead_created, channel_selected (WhatsApp and "call me"), legacy consultation form, validation and protections.
import assert from 'node:assert/strict';
import fs from 'node:fs';
const {onRequest}=await import('./functions/api/lead.js');
const procedures=(await import('./functions/_shared/lead-procedures.js')).default;
assert.ok(procedures.length>0,'procedure allow-list generated by the build');
for(const f of ['functions/api/lead.js','server/lead-handler.mjs','server/call-due.mjs','server/journey.mjs','functions/_shared/lead-procedures.js'])assert.ok(!/from ['"]node:|require\(/.test(fs.readFileSync(f,'utf8')),f+' must not import node: modules (Workers runtime)');
const calls=[];const realFetch=globalThis.fetch;
globalThis.fetch=async(url,init)=>{calls.push({url,init,body:JSON.parse(init.body)});return new Response('{}',{status:200});};
const site='https://fulviocorrea.com';let ipCount=0;
const base={name:'María José López',phone:'+573001234567',phone_country:'CO',phone_country_code:'+57',procedure:procedures[0],procedure_label:'Liposucción',language:'es',contact_consent:true,sms_consent:true,consent_version:'contact-consent-2026-09-27',consent_text:'Acepto que el equipo…',
 page_url:site+'/es/procedures/liposuction/?email=private@example.com',page_title:'Liposucción | Dr. Fulvio Correa',referrer:'https://www.google.com/search?q=x',landing_page:site+'/es/',landing_url_first:site+'/es/',referrer_first:'https://www.google.com/',attribution_timestamp:'2026-09-20T15:00:00.000Z',
 utm_source:'google',utm_medium:'cpc',utm_campaign:'lipo-es',utm_source_first:'google',utm_medium_first:'cpc',utm_campaign_first:'lipo-es',utm_source_last:'google',utm_medium_last:'cpc',utm_campaign_last:'lipo-es',gclid:'Cj0-test',gclid_first:'Cj0-test',gclid_last:'Cj0-test',
 timezone:'America/Bogota',ga_client_id:'123456789.1700000000',measurement_consent:'granted',form_id:'contact-widget',client_timestamp:'2026-09-27T21:00:00.000Z'};
let seq=0;const newId=()=>'lead-test-'+(++seq).toString().padStart(4,'0')+Math.random().toString(36).slice(2,8);
const request=(body,{headers={},ip}={})=>new Request(site+'/api/lead',{method:'POST',headers:{'content-type':'application/json',origin:site,'idempotency-key':body.event_id||body.lead_id,'CF-Connecting-IP':ip||'203.0.113.'+(++ipCount%250),...headers},body:JSON.stringify(body)});
const call=async(req,env)=>{const r=await onRequest({request:req,env});return {status:r.status,body:await r.json()};};
const created=(over={})=>{const lead_id=over.lead_id||newId();return {...base,event:'lead_created',lead_id,event_id:lead_id+'-created',contact_preference:'pending',button_id:'contact-widget-open',...over};};
const channel=(lead_id,ch,over={})=>({...base,event:'channel_selected',lead_id,event_id:lead_id+'-'+ch+(over.preferred_call_time?'-'+over.preferred_call_time:''),channel:ch,contact_preference:ch,button_id:'contact-'+ch,...over});
let r=await call(request(created()),{});assert.equal(r.status,503);assert.equal(r.body.error,'not_configured');assert.equal(calls.length,0);
const env={LEAD_CAPTURE_ENABLED:'true',LEAD_WEBHOOK_URL:'https://services.leadconnectorhq.com/hooks/EXAMPLE/webhook-trigger/EXAMPLE'};
// 1. lead_created
const lead=created();r=await call(request(lead),env);assert.equal(r.status,200);assert.equal(r.body.accepted,true);assert.equal(r.body.lead_id,lead.lead_id);assert.equal(calls.length,1);
let sent=calls[0].body;assert.equal(calls[0].url,env.LEAD_WEBHOOK_URL);assert.equal(calls[0].init.headers['Idempotency-Key'],lead.event_id);assert.equal(calls[0].init.headers['Content-Type'],'application/json');
for(const [k,v] of Object.entries({event:'lead_created',lead_id:lead.lead_id,name:'María José López',first_name:'María',last_name:'José López',phone:'+573001234567',procedure:procedures[0],procedure_label:'Liposucción',language:'es',contact_preference:'pending',channel:'',preferred_call_time:'',call_due_at:'',call_due_at_iso:'',call_window_colombia:'',timezone:'America/Bogota',page_url:site+'/es/procedures/liposuction/',page_path:'/es/procedures/liposuction/',referrer:'https://www.google.com/search',utm_source:'google',utm_campaign_first:'lipo-es',gclid_last:'Cj0-test',fbclid:'',contact_consent:true,consent_version:'contact-consent-2026-09-27',deduplication_key:'+573001234567',ga_client_id:'123456789.1700000000'}))assert.deepEqual(sent[k],v,'lead_created.'+k);
assert.ok(Object.values(sent).every(v=>typeof v!=='object'),'payload is flat');assert.ok(!JSON.stringify(sent).includes('private@example.com'),'query strings stripped');assert.match(sent.summary,/^Nuevo lead web \(canal pendiente\) \| María José López \| \+573001234567 \| Procedimiento: Liposucción/);assert.match(sent.summary,/Fuente: google \/ cpc \/ lipo-es/);
// 2. channel_selected: WhatsApp (same lead_id and phone)
r=await call(request(channel(lead.lead_id,'whatsapp')),env);assert.equal(r.status,200);sent=calls[1].body;assert.equal(sent.event,'channel_selected');assert.equal(sent.lead_id,lead.lead_id);assert.equal(sent.phone,'+573001234567');assert.equal(sent.contact_preference,'whatsapp');assert.equal(sent.preferred_call_time_label,'');assert.equal(sent.call_due_at,'');assert.equal(sent.call_due_at_iso,'');assert.equal(sent.call_window_colombia,'');assert.match(sent.summary,/^Eligió WhatsApp/);assert.ok(!sent.summary.includes('Llamar:'));
// 3. channel_selected: call me with preferred time window and time zone
r=await call(request(channel(lead.lead_id,'call',{preferred_call_time:'morning'})),env);assert.equal(r.status,200);sent=calls[2].body;
for(const [k,v] of Object.entries({channel:'call',contact_preference:'call',preferred_call_time:'morning',preferred_call_time_label:'Mañana / Morning (8:00–12:00)',timezone:'America/Bogota'}))assert.equal(sent[k],v,'call.'+k);
assert.match(sent.summary,/^Solicitud de llamada \| María José López \| \+573001234567 \| Procedimiento: Liposucción \| Horario preferido: Mañana \/ Morning \(8:00–12:00\), hora local del paciente \(America\/Bogota\)/);
assert.match(sent.call_due_at,/^\d{2}-\d{2}-\d{4} \d{2}:\d{2} [AP]M$/);assert.match(sent.call_due_at_iso,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);assert.ok(sent.summary.endsWith(' | Llamar: '+sent.call_window_colombia));
// Validation of the new fields and events
for(const bad of [channel(lead.lead_id,'call'),channel(lead.lead_id,'call',{preferred_call_time:'midnight'}),channel(lead.lead_id,'telegram'),{...channel(lead.lead_id,'whatsapp'),channel:''},created({event:'lead_deleted'}),created({language:'fr'}),created({procedure:'unknown'}),created({phone:'3001234567'}),created({contact_consent:false})]){r=await call(request(bad),env);assert.equal(r.status,422,JSON.stringify(bad).slice(0,80));}
r=await call(request(created(),{headers:{'idempotency-key':'something-else'}}),env);assert.equal(r.status,422,'Idempotency-Key must equal event_id');
r=await call(request(created({timezone:'<script>'})),env);assert.equal(r.status,200);assert.equal(calls.at(-1).body.timezone,'','invalid timezone dropped');
// Idempotency: identical retry is not forwarded twice; same event_id with other data conflicts
const before=calls.length,retry=created();r=await call(request(retry),env);r=await call(request({...retry,client_timestamp:'2026-09-27T21:00:05.000Z'}),env);assert.equal(r.status,200);assert.equal(calls.length,before+1,'retry deduplicated');
r=await call(request({...retry,name:'Someone Else'}),env);assert.equal(r.status,409);
// Legacy consultation form (no event, first_touch/last_touch JSON strings) keeps working
const legacyId=newId();r=await call(request({name:'Test Person',phone:'+15555550123',email:'t@example.com',procedure:procedures[0],language:'en',contact_consent:true,lead_id:legacyId,first_touch:JSON.stringify({utm_source:'first',landing_page:site+'/en/',timestamp:'2026-09-01T00:00:00.000Z'}),last_touch:JSON.stringify({utm_source:'bing',gclid:'g1'})}),env);
assert.equal(r.status,200);sent=calls.at(-1).body;assert.equal(sent.event,'lead_created');assert.equal(sent.event_id,legacyId);assert.equal(sent.utm_source_first,'first');assert.equal(sent.utm_source,'bing');assert.equal(sent.gclid_last,'g1');assert.equal(sent.landing_url_first,site+'/en/');assert.equal(sent.attribution_timestamp,'2026-09-01T00:00:00.000Z');
// Event sign-up (event-view.mjs / event-signup.js): allow-listed event_tag, city and companion reach the webhook flat, with a readable summary.
{const tag='charla-mommy-makeover-doral-oct2026';const ev=o=>created({procedure:'mommy-makeover',email:'test@example.com',city:'Doral',companion:'yes',event_tag:tag,form_id:'event-signup',...o});
 const before=calls.length;r=await call(request(ev()),env);assert.equal(r.status,200);sent=calls.at(-1).body;assert.equal(calls.length,before+1);
 for(const [k,v] of Object.entries({event_tag:tag,tags:tag,city:'Doral',companion:'yes',lead_source_detail:'event_signup',email:'test@example.com',lead_source:'website'}))assert.equal(sent[k],v,'event '+k);
 assert.match(sent.summary,/^Registro evento: .*Doral/);assert.match(sent.summary,/Ciudad: Doral \| Acompañante: Sí/);assert.match(sent.summary,/Tag: charla-mommy-makeover-doral-oct2026/);
 assert.equal(sent.procedure,'mommy-makeover');assert.equal(sent.procedure_interest,undefined,'interest omitted when blank');
 r=await call(request(ev({procedure_interest:'breast'})),env);assert.equal(r.status,200);sent=calls.at(-1).body;
 assert.equal(sent.procedure,'mommy-makeover');assert.equal(sent.procedure_interest,'breast');assert.equal(sent.procedure_interest_label,'Busto / Breast');assert.match(sent.summary,/Interés: Busto \/ Breast/);
 r=await call(request(ev({procedure_interest:''})),env);assert.equal(r.status,200);assert.equal(calls.at(-1).body.procedure_interest,undefined,'empty interest stays off the payload');
 for(const bad of [{event_tag:'other-tag'},{email:''},{city:''},{companion:'maybe'},{companion:''},{procedure_interest:'implants'}]){r=await call(request(ev(bad)),env);assert.equal(r.status,422,'event '+JSON.stringify(bad));}
 r=await call(request(created({companion:'yes'})),env);assert.equal(r.status,422,'companion without event_tag');
 r=await call(request(created({procedure_interest:'not-a-procedure'})),env);assert.equal(r.status,422,'invalid interest on a regular lead');
 r=await call(request(created()),env);assert.equal(r.status,200);assert.equal(calls.at(-1).body.event_tag,undefined,'regular leads unchanged');assert.equal(calls.at(-1).body.procedure_interest,undefined);}
// Protections
r=await call(request(created({website:'spam'})),env);assert.equal(r.status,400,'honeypot');
r=await call(request(created(),{headers:{origin:'https://evil.example'}}),env);assert.equal(r.status,403);
r=await call(new Request(site+'/api/lead'),env);assert.equal(r.status,405);
r=await call(request(created()),{...env,LEAD_WEBHOOK_URL:'http://insecure.example/hook'});assert.equal(r.status,503);
r=await call(request(created()),{...env,LEAD_CAPTURE_ENABLED:'false'});assert.equal(r.status,503);
const statuses=[];for(let i=0;i<11;i++)statuses.push((await call(request(created(),{ip:'198.51.100.7'}),env)).status);assert.deepEqual(statuses,[...Array(10).fill(200),429],'10 requests/min per IP');
globalThis.fetch=async()=>new Response('',{status:500});r=await call(request(created()),env);assert.equal(r.status,502);assert.equal(r.body.error,'delivery_unconfirmed');
globalThis.fetch=realFetch;
console.log('PASS: Cloudflare /api/lead function: lead_created, channel_selected (WhatsApp, call with time window), flat payload with summary, attribution first/last, legacy form, idempotency, validation, honeypot, origin, rate limit, 503 when disabled, non-HTTPS webhook and upstream failures, event sign-ups (event_tag/city/companion).');
