import {webvtt} from './subtitles.mjs';
import {read,write,esc} from './editorial.mjs';
export const patientVideos=()=>read('data/patient-videos.json');
const stamp=s=>new Date(Math.round(s*1000)).toISOString().slice(11,23);
export function patientCards(lang){const es=lang==='es';return `<div class="team-grid">${patientVideos().map(v=>`<a class="team-card" href="/${lang}/testimonials/${v.slug}/"><img src="${v.poster}" width="${v.width}" height="${v.height}" alt="${esc(v.name)}" loading="lazy" decoding="async"><div><p class="eyebrow">${es?'Ver experiencia':'Watch patient story'} · ${Math.floor(v.duration/60)}:${String(v.duration%60).padStart(2,'0')}</p><h3>${esc(v.name)}</h3><p>${esc(v.summary[lang])}</p></div></a>`).join('')}</div>`;}
export function patientWatch(v,lang,origin){
 const es=lang==='es',cues=read(`content/videos/${v.slug}.json`),title=es?`La experiencia de ${v.name}`:`${v.name}’s patient experience`;
 for(const l of ['en','es'])write(`dist/assets/${v.slug}-${l}.vtt`,webvtt(cues,l));
 const body=`<section class="page-hero wrap"><p class="eyebrow">${es?'Experiencias de pacientes':'Patient experiences'}</p><h1>${title}</h1><p>${esc(v.summary[lang])}</p></section><section class="section wrap no-top"><figure class="lipo-video patient-film"><video controls playsinline preload="none" width="${v.width}" height="${v.height}" poster="${v.poster}" aria-label="${esc(title)}"><source src="${v.file}" type="video/mp4">${['es','en'].map(l=>`<track kind="subtitles" src="/assets/${v.slug}-${l}.vtt" srclang="${l}" label="${l==='es'?'Español':'English'}"${l===lang?' default':''}>`).join('')}<a href="https://www.youtube.com/watch?v=${v.youtubeId}">YouTube</a></video><figcaption>${es?'Audio original en español. Subtítulos disponibles en español e inglés. Incluye imágenes del proceso quirúrgico. Cada experiencia es individual y no garantiza resultados.':'Original Spanish audio. Spanish and English subtitles available. Includes footage of the surgical process. Each experience is individual and does not guarantee outcomes.'}</figcaption></figure><p><a class="textlink" href="https://www.youtube.com/watch?v=${v.youtubeId}" target="_blank" rel="noopener">${es?'Video original en el canal del doctor':'Original video on the doctor’s channel'} ↗</a></p><details><summary>${es?'Leer la transcripción':'Read the translated transcript'}</summary><p>${es?'Transcripción editada para facilitar la lectura. Los fragmentos que no se distinguen se indican como no inteligibles.':'Translation edited for readability. Indistinct passages are marked as unintelligible.'}</p>${cues.map(c=>`<p><small>${stamp(c.start).slice(3,8)}</small> ${esc(c[lang])}</p>`).join('')}</details><p><a href="/${lang}/testimonials/">${es?'Todas las experiencias':'All patient experiences'}</a></p><a class="button" data-cta="patient-story-consult" href="/${lang}/book-consultation/">${es?'Conversar sobre mi valoración':'Discuss my consultation'}</a></section>`;
 return {title,description:v.summary[lang],body,schemas:[{'@context':'https://schema.org','@type':'VideoObject','@id':origin+`/${lang}/testimonials/${v.slug}/#video`,name:v.originalTitle,description:v.summary[lang],thumbnailUrl:origin+v.poster,uploadDate:v.uploadDate,duration:`PT${v.duration}S`,contentUrl:origin+v.file,inLanguage:'es',transcript:cues.map(c=>c[lang]).join(' '),mainEntityOfPage:origin+`/${lang}/testimonials/${v.slug}/`,publisher:{'@id':origin+'/#physician'}}]};
}
