const team=JSON.parse(fs.readFileSync('data/team.json','utf8'));
const teamImages=imageMeta();
const homeHero=JSON.parse(fs.readFileSync('data/home-hero.json','utf8'));
import {physicianNode,membershipView} from './practice-view.mjs';
import {seo,assertSeoCopy} from './seo-copy.mjs';
import fs from 'node:fs';import path from 'node:path';import {copy,procedures} from './content.mjs';import {imageMeta} from './assets.mjs';import {robotsTxt} from './site-env.mjs';
assertSeoCopy();
const practice=JSON.parse(fs.readFileSync('data/practice.json','utf8'));
const config={...JSON.parse(fs.readFileSync('config.json','utf8')),production:process.env.SITE_ENV==='production'},origin=config.origin,official='https://fulviocorrea.com.co',pages=[];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const image=(file,alt='',cls='',priority=false)=>`<img class="${cls}" src="/assets/${file}" alt="${esc(alt)}" width="${file==='hero-woman-floral-portrait.webp'?1920:660}" height="${file==='hero-woman-floral-portrait.webp'?1040:750}" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
for(const lang of ['en','es']){
 const t=copy[lang],i=lang==='en'?0:1,url=(slug='')=>`/${lang}/${slug}`,tag=text=>`<p class="eyebrow">${text}</p>`;
 const button=(id,label=t.consult,href=url('book-consultation/'),light=false)=>`<a class="button${light?' light':''}" id="${id}" data-cta="${id}" data-event="${href.includes('book-consultation')?'consultation_click':'navigation_click'}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
 const link=(text,href)=>`<a class="textlink" href="${href}">${text}<span aria-hidden="true">↗</span></a>`;
 const faq=()=>t.faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
 const s=seo[lang];
 const brand=`<img src="/assets/dr-fulvio-correa-logo.png" width="290" height="290" alt="${lang==='en'?'Dr. Fulvio Correa · Plastic Surgeon':'Dr. Fulvio Correa · Cirujano plástico'}">`;
 const header=slug=>`<div class="topline">${t.top}</div><header class="site-header"><a class="brand" href="${url()}" aria-label="${t.home}">${brand}</a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">${t.menu}<span aria-hidden="true">☰</span></button><nav class="nav" id="navigation" aria-label="${lang==='en'?'Main navigation':'Navegación principal'}"><a href="${url()}">${t.home}</a>${t.nav.map((n,k)=>`<a href="${url(['about/','procedures/','international-patients/','resources/'][k])}">${n}</a>`).join('')}<div class="language-picker" aria-label="${lang==='en'?'Language':'Idioma'}"><a href="/en/${slug}" data-language="en" lang="en" ${lang==='en'?'aria-current="true"':''}>EN</a><span>/</span><a href="/es/${slug}" data-language="es" lang="es" ${lang==='es'?'aria-current="true"':''}>ES</a></div>${button('header-consult')}</nav></header>`;
 const footer=`<footer><div class="footer-grid wrap"><div><a class="brand footer-brand" href="${url()}">${brand}</a><p>${t.location}<br>${lang==='en'?'Facial · Breast · Body':'Rostro · Mamas · Cuerpo'}</p></div><div>${tag(lang==='en'?'Explore':'Explorar')}${[['procedures/',t.nav[1]],['international-patients/',t.nav[2]],['before-after/',t.beforeAfter],['resources/',t.resources],['faq/',t.faq]].map(([s,n])=>`<a href="${url(s)}">${n}</a>`).join('')}</div><div>${tag(lang==='en'?'Visit the practice':'Visita el consultorio')}<p>${practice.addressLines.map(esc).join('<br>')}</p><a id="footer-whatsapp" data-cta="footer-whatsapp" data-event="whatsapp_click" href="${config.whatsapp}" target="_blank" rel="noopener">${t.whatsapp} ↗</a></div></div><div class="footer-bottom wrap"><p>© ${new Date().getFullYear()} Dr. Fulvio Correa. ${t.footerNote}</p><div><a href="${official}/privacy-policy-1485">${t.privacy}</a><button class="privacy-button" id="privacy-settings">${t.preferences}</button><a href="${url('image-sources/')}">${t.sources}</a></div><p class="preview-note">${t.footerPreview}</p></div></footer><a class="sticky-mobile" id="mobile-consult" data-event="consultation_click" data-cta="mobile-consult" href="${url('book-consultation/')}">${t.consult} ↗</a><aside class="consent-banner" id="cookie-banner" aria-label="${t.preferences}" hidden><p>${t.cookie}</p><button id="accept-analytics">${t.accept}</button><button id="reject-analytics">${t.reject}</button></aside>`;
 const ending=()=>`<section class="closing"><div class="wrap closing-inner">${tag(t.closingLabel)}<h2>${t.closingTitle}</h2><p>${t.closingText}</p>${button('closing-consult')}</div>${image('banner-woman-shoulders.webp','','closing-image')}</section>`;
 const intro=(label,title,lead,slogan='')=>`<section class="page-hero wrap"><div class="crumb"><a href="${url()}">${t.home}</a><span>/</span>${label}</div>${tag(label)}${slogan?`<p class="slogan">${slogan}</p>`:''}<h1>${title}</h1><p class="lead">${lead}</p></section>`;
 const cards=()=>procedures.map((p,n)=>`<a class="procedure-card" href="${url('procedures/'+p.slug+'/')}"><div class="card-image">${image(p.image)}<span class="card-index">0${n+1}</span></div><div class="card-heading"><div><p>${p.category[i]}</p><h3>${p[lang]}</h3></div><span class="circle-arrow" aria-hidden="true">↗</span></div></a>`).join('');
 function page(slug,title,description,body,{home=false,ads=false,faqSchema=false,noindex=false}={}){
 const route=url(slug),canonical=origin+route;
 const schema=[physicianNode(practice,origin,lang),...(!home?[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:t.home,item:origin+url()},{'@type':'ListItem',position:2,name:title,item:canonical}]}]:[]),...(faqSchema?[{'@context':'https://schema.org','@type':'FAQPage',mainEntity:t.faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]:[])];
 const html=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Dr. Fulvio Correa</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${!config.production||ads||noindex?'noindex, nofollow':'index, follow'}"><meta name="theme-color" content="#1c2523"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="${origin+'/en/'+slug}"><link rel="alternate" hreflang="es" href="${origin+'/es/'+slug}"><link rel="alternate" hreflang="x-default" href="${origin+'/en/'+slug}"><meta property="og:title" content="${esc(title)} | Dr. Fulvio Correa"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="${lang==='en'?'en_US':'es_CO'}"><link rel="preload" href="/assets/fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/aboreto.woff2" as="font" type="font/woff2" crossorigin><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest"><link rel="stylesheet" href="/style.css"><script type="application/ld+json">${JSON.stringify(schema)}</script><script src="/config.js" defer></script><script src="/app.js" defer></script></head><body class="${home?'home ':''}${ads?'ads':''}" data-language="${lang}"><a class="skip" href="#main">${lang==='en'?'Skip to content':'Ir al contenido'}</a>${header(slug)}<main id="main">${body}</main>${footer}</body></html>`;
 const file=path.join('dist',route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);pages.push({route,file,ads,lang,noindex});return html;
 }
 const hero=`<section class="hero${homeHero.image==='hero-purple-trial.webp'?' hero-photo-trial':''}">${image(homeHero.image,s.homeH1,'hero-image',true)}<div class="hero-shade"></div><div class="hero-content wrap">${tag(t.heroLabel)}<h1>${s.homeH1}</h1><p class="slogan">${t.heroTitle}</p><div class="hero-bottom"><p>${t.heroText}</p><div class="hero-actions">${button('hero-consult')}${link(t.discover,url('about/'))}</div></div></div><div class="hero-caption"><span>${t.location}</span><a href="#procedures">${t.scroll} ↓</a></div></section>`;
 const education=`<div class="education"><div><small>${t.education[0]}</small><p>${t.education[1]}</p></div><div><small>${t.education[2]}</small><p>${t.education[3]}</p></div></div>`;
 const resources=`<div class="resource-grid">${t.resourceCards.map(([title,desc,label],n)=>`<a class="resource-card" href="${url(['resources/your-consultation/','international-patients/','faq/'][n])}"><div>${image(['portrait-woman-hands-on-cheeks.webp','banner-woman-shoulders.webp','portrait-woman-hand-on-neck.webp'][n])}</div>${tag(label)}<h3>${title}</h3><p>${desc}</p><span class="textlink">${t.read} ↗</span></a>`).join('')}</div>`;
 const homeBody=hero+`<div class="trust-strip">${t.strip.map(x=>`<span>${x}</span>`).join('<b aria-hidden="true">✧</b>')}</div><section class="section wrap" id="procedures"><div class="section-heading"><div>${tag(t.proceduresLabel)}<h2>${t.proceduresTitle}</h2></div><div><p>${t.proceduresText}</p>${link(t.allProcedures,url('procedures/'))}</div></div><div class="procedure-grid">${cards()}</div></section>
 <section class="doctor-section wrap section"><div class="doctor-photo">${image('dr-fulvio-correa-plastic-surgeon-cartagena.webp','Dr. Fulvio Correa')}<span class="image-signature">Dr. Fulvio Correa</span></div><div class="doctor-copy">${tag(t.doctorLabel)}<h2>${t.doctorTitle}</h2><p>${t.doctorText}</p>${education}${membershipView(practice,lang)}${link(t.doctorLink,url('about/'))}</div></section>
 <section class="philosophy section"><div class="wrap"><div class="philosophy-top">${tag(t.philosophyLabel)}<h2>${t.philosophyTitle}</h2><p>${t.philosophyText}</p></div><div class="steps">${t.steps.map(([h,p],n)=>`<div class="step"><span>0${n+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div></div></section>
 <section class="results section wrap"><div>${tag(t.resultsLabel)}<h2>${t.resultsTitle}</h2><p>${t.resultsText}</p>${link(t.resultsLink,url('before-after/'))}</div><div class="results-frame"><span class="results-monogram" aria-hidden="true">FC</span><p>${t.resultsNote}</p><span class="small-label">${lang==='en'?'INDIVIDUAL STORIES · INDIVIDUAL OUTCOMES':'HISTORIAS INDIVIDUALES · RESULTADOS INDIVIDUALES'}</span></div></section>
 <section class="featured"><div class="featured-image">${image('torso-black-swimsuit.webp')}</div><div class="featured-copy">${tag(t.featureLabel)}<h2>${t.featureTitle}</h2><p>${t.featureText}</p>${button('featured-liposuction',t.featureLink,url('procedures/liposuction/'))}</div></section>
 <section class="international section wrap"><div>${tag(t.internationalLabel)}<h2>${t.internationalTitle}</h2><p>${t.internationalText}</p>${link(t.internationalLink,url('international-patients/'))}</div><div class="journey">${t.journey.map(([h,p],n)=>`<div><span>0${n+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}<p class="coordinates">CARTAGENA DE INDIAS<br>COLOMBIA · ${lang==='en'?'CARIBBEAN COAST':'COSTA CARIBE'}</p></div></section>
 <section class="team-section section"><div class="wrap"><div class="section-heading"><div>${tag(t.teamLabel)}<h2>${t.teamTitle}</h2></div><p>${t.teamText}</p></div><div class="team-grid">${team.members.map(m=>{const photo=m.photoPlaceholder?'':`<img src="/assets/${m.image}" alt="${esc(m.name)}" width="${teamImages[m.image].width}" height="${teamImages[m.image].height}" loading="lazy" decoding="async">`;const mark=m.photoPlaceholder?`<div class="team-placeholder" aria-hidden="true"><span>${esc(m.name.slice(0,1))}</span></div>`:'';return `<article class="team-card${m.photoPlaceholder?' team-card-no-photo':''}">${photo}${mark}<div><h3>${m.about?`<a href="${url('about/')}">${esc(m.name)}</a>`:esc(m.name)}</h3><p>${esc(m.role[lang])}</p></div></article>`;}).join('')}<div class="team-message"><span class="large-quote" aria-hidden="true">“</span><h3>${lang==='en'?'A conversation that<br>starts with you.':'Una conversación<br>que comienza por ti.'}</h3>${button('team-consult',t.consult,url('book-consultation/'),true)}</div></div></div></section>
 <section class="testimonials section wrap"><div>${tag(t.testimonialLabel)}<h2>${t.testimonialTitle}</h2><p>${t.testimonialText}</p></div><figure><blockquote>${t.testimonialQuote}</blockquote><figcaption>${t.testimonialBy}</figcaption><p class="small-label">${t.testimonialNote}</p><a class="source-link" href="${official}/plastic-surgery-colombia-cartagena-liposuction" target="_blank" rel="noopener">${t.source} ↗</a></figure></section>
 <section class="pricing section"><div class="wrap pricing-grid"><div>${tag(t.pricingLabel)}<h2>${t.pricingTitle}</h2><p>${t.pricingText}</p></div><div>${t.pricingItems.map((x,n)=>`<div class="pricing-row"><span>0${n+1}</span><p>${x}</p><span aria-hidden="true">✧</span></div>`).join('')}${button('pricing-consult')}</div></div></section>
 <section class="section wrap"><div class="section-heading"><div>${tag(t.resourcesLabel)}<h2>${t.resourcesTitle}</h2></div>${link(t.resources,url('resources/'))}</div>${resources}</section><section class="faq-section section wrap"><h2>${t.faqTitle}</h2><div>${faq()}</div></section>`+ending();
 page('',s.homeTitle,s.homeDesc,homeBody,{home:true,faqSchema:true});
 page('procedures/',s.proceduresTitle,s.proceduresDesc,intro(t.nav[1],s.proceduresH1,t.proceduresText,t.proceduresTitle)+`<section class="section wrap no-top"><h2>${s.proceduresH2}</h2><div class="procedure-grid all-procedures">${cards()}</div><p class="note">${t.medicalNote}</p></section>`+ending());
 for(const p of procedures){
 page('procedures/'+p.slug+'/',p[lang]+' '+t.procedureTitle,p.description[i],intro(p.category[i],p[lang]+'.<br><em>'+t.procedureTitle+'</em>',p.description[i])+`<section class="section wrap no-top detail-grid"><div class="detail-image">${image(p.image)}</div><article><h2>${lang==='en'?'Your consultation<br>comes first.':'Tu valoración<br>es el comienzo.'}</h2><p>${t.procedureBody}</p><h3>${t.questionsTitle}</h3><ul class="question-list">${t.questions.map(q=>`<li>${q}</li>`).join('')}</ul>${button('procedure-consult')}<p class="note">${t.medicalNote}</p>${link(t.internationalLink,url('international-patients/'))}<p class="source"><a href="${official}/plastic-surgery-colombia-cartagena-${p.slug}">${t.source} ↗</a></p></article></section>`+ending());
 page('ads/'+p.slug+'/',p[lang]+' · '+t.location,p.description[i],`<section class="ads-hero wrap"><div>${tag(t.location)}<h1>${p[lang]}.<br><em>${lang==='en'?'Personally considered.':'Una mirada personal.'}</em></h1><p>${t.procedureBody}</p>${button('ads-consult',t.consult,url('book-consultation/?procedure='+p.slug))}<p class="small-label">${t.strip[1]}</p></div><div>${image(p.image,'','',true)}</div></section><section class="wrap ads-details"><h2>${t.questionsTitle}</h2><ul>${t.questions.map(q=>`<li>${q}</li>`).join('')}</ul><p class="note">${t.medicalNote}</p></section>`,{ads:true});
 }
 page('about/',s.aboutTitle,s.aboutDesc,intro(t.nav[0],s.aboutH1,t.doctorText,lang==='en'?'A personal perspective.':'Una perspectiva personal.')+`<section class="section wrap no-top detail-grid"><div class="doctor-photo">${image('dr-fulvio-correa-plastic-surgeon-cartagena.webp','Dr. Fulvio Correa')}</div><article><h2>${t.doctorTitle}</h2>${education}${membershipView(practice,lang)}<p>${t.philosophyText}</p><p class="source"><a href="${official}/plastic-surgery-colombia-cartagena-staff">${t.source} ↗</a></p>${button('doctor-consult')}</article></section>`+ending());
 page('international-patients/',s.intlH1,t.internationalText,intro(t.nav[2],s.intlH1,t.internationalText,t.travelTitle)+`<section class="section wrap no-top"><div class="travel-grid">${t.journey.map(([h,p],n)=>`<article><span class="number">0${n+1}</span><h2>${h}</h2><p>${p}</p></article>`).join('')}</div><div class="travel-checklist"><h2>${t.questionsTitle}</h2><ul>${t.travelQuestions.map(q=>`<li>${q}</li>`).join('')}</ul>${button('travel-consult')}</div></section>`+ending());
 page('before-after/',t.beforeAfter,t.resultsText,intro(t.beforeAfter,t.resultsTitle,t.resultsText)+`<section class="section wrap no-top"><div class="results-frame results-full"><span class="results-monogram" aria-hidden="true">FC</span><p>${t.resultsNote}</p>${button('results-consult')}</div></section>`+ending(),{noindex:true});
 page('resources/',s.resourcesTitle,s.resourcesDesc,intro(t.resources,s.resourcesH1,t.guideText,t.resourcesTitle)+`<section class="section wrap no-top"><h2>${s.resourcesH2}</h2>${resources}</section>`);
 page('resources/your-consultation/',s.consultTitle,s.consultDesc,intro(t.resourceCards[0][2],s.consultH1,t.guideText,t.guideTitle)+`<article class="section wrap no-top article"><p class="lead">${t.guideBody}</p><h2>${t.questionsTitle}</h2><ul class="question-list">${t.questions.map(q=>`<li>${q}</li>`).join('')}</ul><p class="note">${t.formPrivate}</p>${button('guide-consult')}</article>`+ending());
 page('faq/',s.faqTitle,s.faqDesc,intro(t.faq,s.faqH1,t.philosophyText,t.faqTitle)+`<section class="section wrap no-top article">${faq()}</section>`+ending(),{faqSchema:true});
 const fields=['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','gbraid','wbraid','landing_page','referrer','first_touch','last_touch','conversion_page','lead_id'];
 page('book-consultation/',t.consult,t.contactText,intro(t.consult,t.contactTitle,t.contactText)+`<section class="section wrap no-top consult-grid"><div><h2>${t.closingTitle}</h2><p>${t.closingText}</p><a class="textlink" id="consult-whatsapp" data-event="whatsapp_click" data-cta="consult-whatsapp" href="${config.whatsapp}" target="_blank" rel="noopener">${t.whatsapp} ↗</a><p class="note">${config.leadEndpoint?t.formPrivate:t.preview}</p></div><form id="consultation-form" data-form="consultation" data-event="form_submit"><label>${t.formLabels[0]}<input name="name" autocomplete="name" maxlength="100" required></label><label>${t.formLabels[1]}<input name="email" type="email" autocomplete="email" maxlength="254" required></label><label>${t.formLabels[2]}<input name="phone" type="tel" autocomplete="tel" maxlength="30" required></label><label>${t.formLabels[3]}<select name="procedure"><option value="undecided">${t.formLabels[4]}</option>${procedures.map(p=>`<option value="${p.slug}">${p[lang]}</option>`).join('')}</select></label><label class="consent"><input type="checkbox" name="contact_consent" required><span>${t.consent} <a href="${official}/privacy-policy-1485" target="_blank" rel="noopener">${t.privacy}</a>.</span></label>${fields.map(n=>`<input type="hidden" name="${n}">`).join('')}<input type="hidden" name="language" value="${lang}"><button class="button" id="submit-consultation" type="submit">${config.leadEndpoint?t.send:t.formButton}<span>↗</span></button><p id="form-status" class="form-status" role="status" aria-live="polite"></p></form></section>`);
 const photoFiles=[['hero-woman-floral-portrait.webp','84-home-1-1.webp'],['portrait-woman-hand-on-neck.webp','84-home-1-2.webp'],['torso-black-swimsuit.webp','84-home-1-7.webp'],['face-with-eyelid-markings.webp','84-home-1-8.webp'],['back-view-beige-bodysuit.webp','84-home-1-9.webp'],['portrait-woman-hands-on-cheeks.webp','84-home-1-10.webp'],['banner-woman-shoulders.webp','84-home-1-11.webp']];
 page('image-sources/',t.sources,t.footerPreview,intro(t.sources,lang==='en'?'Photography &<br><em>image sources.</em>':'Fotografía y<br><em>fuentes visuales.</em>',t.footerPreview)+`<section class="section wrap no-top"><div class="article"><p>${lang==='en'?'The Rejuvita demo credits link to Freepik sources. A source link alone does not establish a reuse license. These images are provisional for design review and must be replaced or appropriately licensed before public launch.':'Los créditos de la demo Rejuvita enlazan a fuentes de Freepik. Un enlace no acredita una licencia de reutilización. Estas imágenes son provisionales para revisar el diseño; deben sustituirse o contar con licencia antes del lanzamiento público.'}</p><p><a class="textlink" href="https://rejuvita.cmsmasters.studio/main/image-credits/" target="_blank" rel="noopener">Rejuvita · Image credits ↗</a></p><p>${lang==='en'?'The logo, doctor and Yarima photographs come from the official Fulvio Correa website.':'El logo y las fotografías del doctor y de Yarima provienen de la web oficial de Fulvio Correa.'}</p></div><div class="source-grid">${photoFiles.map(([f,original])=>`<article>${image(f)}<p>${f}</p><a href="https://rejuvita.cmsmasters.studio/main/wp-content/uploads/sites/2/2026/03/${original}" target="_blank" rel="noopener">${lang==='en'?'Original image':'Imagen original'} ↗</a></article>`).join('')}</div></section>`,{noindex:true});
 const notFound=page('404/',lang==='en'?'Page not found':'Página no encontrada',t.notFound,intro('404','404',t.notFound)+`<section class="wrap section no-top">${button('back-home',t.home,url())}</section>`,{noindex:true});if(lang==='en')fs.writeFileSync('dist/404.html',notFound);
}
for(const p of pages.filter(p=>p.lang==='en')){const oldRoute=p.route.slice(3)||'/',file=path.join('dist',oldRoute,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,fs.readFileSync(p.file,'utf8').replace('<head>','<head><script src="/locale.js"></script>'));}
fs.writeFileSync('dist/config.js','window.SITE_CONFIG='+JSON.stringify(config)+';');
fs.writeFileSync('dist/robots.txt',robotsTxt(config.production,origin));
fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>!p.ads&&!p.noindex).map(p=>`<url><loc>${origin+p.route}</loc></url>`).join('')+'</urlset>');
fs.writeFileSync('dist/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n/assets/*\n  Cache-Control: public, max-age=604800\n');
fs.writeFileSync('pages.json',JSON.stringify(pages,null,2));console.log(`Generated ${pages.length} localized pages plus legacy language entry routes.`);
