import fs from 'node:fs';import path from 'node:path';import {posts,read} from './editorial.mjs';import {text,sentenceSet,similarity} from './validators.mjs';import {localizePath,procedureRoute} from './routes.mjs';
const practice=read('data/practice.json');
const pages=read('pages.json'),data=fs.readdirSync('content/procedures').map(f=>read('content/procedures/'+f)),blog=posts().filter(p=>!p.draft),clusters=read('content/clusters.json'),errors=[],warnings=[],check=(ok,m)=>{if(!ok)errors.push(m);};const htmls=new Map(pages.map(p=>[p.route,fs.readFileSync(p.file,'utf8')])),inbound=new Map(pages.map(p=>[p.route,new Set()]));const production=process.env.SITE_ENV?process.env.SITE_ENV==='production':!/^Disallow: \/\s*$/m.test(fs.readFileSync('dist/robots.txt','utf8'));// standalone `npm test` checks the mode that was actually built
for(const p of pages){const h=htmls.get(p.route),main=h.match(/<main[^>]*>([\s\S]*?)<\/main>/)?.[1]||'';check((h.match(/<h1(?:\s|>)/g)||[]).length===1,p.route+' H1');check(h.includes('rel="canonical" href="https://fulviocorrea.com.co'+p.route+'"'),p.route+' canonical');check(text(h.match(/<title>(.*?)<\/title>/)?.[1]||'').length<=60,p.route+' title >60');for(const key of ['og:image','og:title','og:description','twitter:card'])check(h.includes('"'+key+'"'),p.route+' '+key);check(h.includes('hreflang="x-default"'),p.route+' x-default');check(!/official practice website|web oficial del consultorio|This preview does not send|Patient images will be added/i.test(h),p.route+' old copy');check(h.includes(`name="robots" content="${production&&!p.ads&&!p.noindex?'index, follow':'noindex, nofollow'}"`),p.route+' robots');
for(const m of h.matchAll(/(?:href|src)="(\/[^"<>]*)"/g)){const pathname=decodeURIComponent(m[1].split(/[?#]/)[0]),target=path.join('dist',pathname);check(fs.existsSync(target)&&(!pathname.endsWith('/')||fs.existsSync(path.join(target,'index.html'))),p.route+' broken '+pathname);}
for(const m of h.matchAll(/<a\b([^>]*?)href="([^"]+)"([^>]*)>/g)){const attrs=m[1]+m[3],href=m[2];check(!/^https?:\/\/(?:www\.)?fulviocorrea\.com\.co/.test(href),p.route+' old-domain href');if(!href.startsWith('/'))continue;const dest=href.split(/[?#]/)[0];if(dest!==p.route&&!/data-language/.test(attrs))inbound.get(dest)?.add(p.route);const other=dest.match(/^\/(en|es)\//)?.[1];if(other&&other!==p.lang)check(/data-language/.test(attrs)&&p.alternates.some(a=>a.route===dest),p.route+' wrong-language link '+dest);}
for(const m of h.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{const schemas=JSON.parse(m[1]);const doctors=schemas.filter(x=>x['@id']==='https://fulviocorrea.com.co/#physician');for(const doctor of doctors){if(practice.societies?.length){check(doctor.memberOf?.length===practice.societies.length,p.route+' physician missing memberOf');for(const society of practice.societies)check(JSON.stringify(doctor.memberOf).includes(society.source),p.route+' membership verification missing');}else check(!doctor.memberOf,p.route+' unexpected memberOf');check(JSON.stringify(doctor.sameAs||[])===JSON.stringify(practice.sameAs||[]),p.route+' sameAs changed');}check(doctors.length===1,p.route+' missing or duplicate physician');for(const post of schemas.filter(x=>x['@type']==='BlogPosting'))check(practice.authorApproved?post.author['@id']==='https://fulviocorrea.com.co/#physician':post.author['@type']==='Organization',p.route+' incorrect authorship');const crumb=schemas.find(x=>x['@type']==='BreadcrumbList');if(p.procedure&&!p.ads||blog.some(x=>`/${x.lang}/blog/${x.slug}/`===p.route))check(crumb.itemListElement.length===3,p.route+' breadcrumbs');check(crumb.itemListElement.every(x=>!x.name.includes(' | Dr. Fulvio Correa')),p.route+' breadcrumb suffix');}catch{errors.push(p.route+' invalid JSON-LD');}}
if(!p.ads&&!p.noindex){const words=text(main).split(/\s+/).filter(Boolean).length;if(words<600)warnings.push(p.route+`: ${words} words (<600; content required before launch).`);}
for(const m of h.matchAll(/<img[^>]*src="\/([^\"]+)"[^>]*fetchpriority="high"[^>]*>/g))check(fs.statSync('dist/'+m[1]).size<=200000,'Hero >200KB '+m[1]);}
for(const lang of ['en','es'])for(const society of practice.societies||[]){const h=htmls.get(localizePath('/'+lang+'/about/'));check(h.includes('href="'+society.source+'" target="_blank" rel="noopener"'),lang+' about missing visible membership verification');}
for(const p of pages.filter(p=>!p.noindex&&!p.ads))check(inbound.get(p.route).size>0,p.route+' orphan');
for(const p of blog){const pillar=data.find(d=>d.lang===p.lang&&d.slug===p.procedure),r=`/${p.lang}/blog/${p.slug}/`,pr=procedureRoute(p.lang,p.procedure);check(!!pillar,r+' missing pillar');check(htmls.get(r)?.includes(`href="${pr}"`),r+' no pillar link');check(htmls.get(pr)?.includes(`href="${r}"`),pr+' no link to '+r);check(clusters[p.lang]?.[p.procedure]?.includes(p.slug),r+' cluster map missing');check(p.related.length<=4,r+' too many related');for(const slug of p.related)check(blog.some(x=>x.slug===slug&&x.lang===p.lang),r+' invalid related '+slug);if(p.related.length<2)warnings.push(r+': fewer than 2 same-language articles in this cluster; add reviewed articles.');}
const clinical=data.map(p=>{const h=htmls.get(procedureRoute(p.lang,p.slug))||'',article=(h.match(/<article data-procedure-content>([\s\S]*?)<\/article>/)?.[1]||'').split('<aside data-shared>')[0];return{p,sentences:sentenceSet(article)};});for(let i=0;i<clinical.length;i++)for(let j=i+1;j<clinical.length;j++){const a=clinical[i],b=clinical[j];if(a.p.lang===b.p.lang)check(similarity(a.sentences,b.sentences)<=0.2,`Procedure overlap >20%: ${a.p.slug}/${b.p.slug} (${a.p.lang})`);}
const sitemap=fs.readFileSync('dist/sitemap.xml','utf8');for(const p of data){const r=procedureRoute(p.lang,p.slug);check(sitemap.includes('<loc>https://fulviocorrea.com.co'+r+'</loc>')===p.offeredConfirmed,r+' publication status');check(p.faqs.length>=5,r+' fewer than 5 FAQ slots');if(p.offeredConfirmed&&!p.summary)warnings.push(r+': clinical fields and FAQ answers await approval.');}
for(const p of posts().filter(p=>p.draft)){check(!sitemap.includes('/blog/'+p.slug+'/'),'Draft in sitemap');check(!fs.existsSync('dist/'+p.lang+'/blog/'+p.slug+'/index.html'),'Published draft');}
const redirects=read('migration/redirects.json').redirects;const redirectTargetOk=to=>{const clean=to.split(/[?#]/)[0];return clean.endsWith('/')?fs.existsSync('dist'+clean+'index.html'):fs.existsSync('dist'+clean);};for(const r of redirects){check(redirectTargetOk(r.to),'Redirect target not 200 '+r.to);check(!redirects.some(x=>x.from.endsWith('*')?r.to.startsWith(x.from.slice(0,-1)):x.from===r.to),'Redirect chain '+r.from);check(r.status===301,'Redirect not 301');}const firstDynamic=redirects.findIndex(r=>/[*:]/.test(r.from));if(firstDynamic>=0)check(redirects.slice(firstDynamic).every(r=>/[*:]/.test(r.from)),'Exact redirect after a splat');check(fs.existsSync('dist/_redirects')===production,'Redirect activation mode');check(!/locale\.js|location\.replace/.test(fs.readFileSync('dist/index.html','utf8')),'Root client redirect');
const bytes=['app.js','contact.js','thank-you.js','style.css','config.js'].reduce((n,f)=>n+fs.statSync('dist/'+f).size,0);check(bytes<=64000,'JS+CSS budget '+bytes);const client=['app.js','contact.js','thank-you.js','config.js'].map(f=>fs.readFileSync('dist/'+f,'utf8')).join('');check(!/AW-\d|googleadservices|doubleclick\.net|googlesyndication/.test(client),'Ads tags detected');check(!client.includes('LEAD_WEBHOOK_URL')&&!/https:\/\/[^"\s]*(?:leadconnector|highlevel)[^"\s]*/i.test(client),'Webhook exposed');check(read('config.json').origin.startsWith('https://'),'Absolute origin');
fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/verification.json',JSON.stringify({mode:production?'production':'preview',pages:pages.length,bytes,errors,warnings},null,2));
if(errors.length)throw Error(errors.join('\n'));console.log(`PASS: ${pages.length} pages; metadata, links, clusters, publication, redirects, similarity, drafts and budgets. JS + CSS: ${bytes} bytes.`);console.log(`WARN: ${warnings.length} editorial warnings; see reports/verification.json. No content or ranking guarantee.`);
