CREATE TABLE IF NOT EXISTS leads (
  event_id TEXT PRIMARY KEY,
  lead_id TEXT NOT NULL,
  received_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  event TEXT NOT NULL,
  event_slug TEXT NOT NULL DEFAULT '',
  event_tag TEXT NOT NULL DEFAULT '',
  language TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  procedure TEXT NOT NULL DEFAULT '',
  procedure_label TEXT NOT NULL DEFAULT '',
  procedure_interest TEXT NOT NULL DEFAULT '',
  procedure_interest_label TEXT NOT NULL DEFAULT '',
  companion TEXT NOT NULL DEFAULT '',
  form_id TEXT NOT NULL DEFAULT '',
  page_path TEXT NOT NULL DEFAULT '',
  page_url TEXT NOT NULL DEFAULT '',
  utm_source TEXT NOT NULL DEFAULT '',
  utm_medium TEXT NOT NULL DEFAULT '',
  utm_campaign TEXT NOT NULL DEFAULT '',
  utm_term TEXT NOT NULL DEFAULT '',
  utm_content TEXT NOT NULL DEFAULT '',
  gclid TEXT NOT NULL DEFAULT '',
  gbraid TEXT NOT NULL DEFAULT '',
  wbraid TEXT NOT NULL DEFAULT '',
  fbclid TEXT NOT NULL DEFAULT '',
  ip_country TEXT NOT NULL DEFAULT '',
  webhook_status TEXT NOT NULL DEFAULT 'pending',
  webhook_http_status INTEGER,
  payload_json TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS leads_received_at ON leads (received_at);
CREATE INDEX IF NOT EXISTS leads_event_slug ON leads (event_slug);
